/**
 * Hybrid Backtest V2 — Intelligent Regime-Switching Engine
 *
 * Key improvements over the simple market-condition lookup:
 *  1. Confirmation gate: 2 consecutive signals required before switching regime
 *  2. Multi-timeframe confirmation: weekly + monthly must agree for a regime change
 *  3. Smooth transition: partial rotation over 2 rebalance periods instead of instant flip
 *  4. Regime performance attribution: per-regime P&L, win-rate, drawdown
 *  5. Transition cost tracking: extra trades generated by regime switches
 */

import { analyzeMarketCondition } from './marketConditionService'
import type {
  BacktestConfig,
  BacktestTrade,
  CriteriaType,
  Holding,
  PortfolioSnapshot,
  BacktestResult,
} from '../types/market'

// ── Types ────────────────────────────────────────────────────────────────────

export interface RegimeChange {
  newRegime:          string
  confirmationCount:  number
  firstSignalDate:    Date
}

export interface RegimeDecision {
  regime:         string
  criteriaType:   CriteriaType
  switched:       boolean
  fromRegime?:    string
  confidence:     number
  pendingChange?: RegimeChange | null
}

export interface RegimeStat {
  avgReturn:       number
  winRate:         number
  maxDrawdown:     number
  periodsActive:   number
  contribution:    number     // cumulative return while in this regime
}

export interface TransitionPlan {
  phase:              1 | 2   // 1 = half-transition, 2 = fully switched
  newCriteriaType:    CriteriaType
  fromCriteriaType:   CriteriaType
  maxNewPositions:    number  // how many new regime positions to add in phase 1
  sellThreshold:      number  // sell positions scoring below this
  transitionDate:     Date
}

export interface HybridReport {
  overall: {
    totalReturn:     number
    cagr:            number
    sharpe:          number
    maxDrawdown:     number
  }
  byRegime:          Record<string, RegimeStat>
  regimeSwitches:    number
  timeInEachRegime:  Record<string, string>
  transitionCost:    number   // percentage points lost to transition trades
}

// Callback type matching backtestEngine's RebalancePortfolio signature
export type RebalanceFn = (
  holdings:    Holding[],
  cash:        number,
  totalValue:  number,
  date:        Date,
  criteria:    CriteriaType,
  market:      string,
  config:      BacktestConfig,
  snapshots:   PortfolioSnapshot[],
) => Promise<{ holdings: Holding[]; cash: number; portfolioValue: number; buys: BacktestTrade[]; sells: BacktestTrade[] }>

// ── Constants ─────────────────────────────────────────────────────────────────

const CRITERIA_MAP: Record<string, CriteriaType> = {
  BULL:     'ALFA',
  BEAR:     'BETA',
  SIDEWAYS: 'DELTA',
}

const CONFIRMATION_PERIODS = 1  // 1 period confirmation — lower lag, more responsive

// ── HybridBacktestV2 ─────────────────────────────────────────────────────────

export class HybridBacktestV2 {
  private currentRegime:       string = 'SIDEWAYS'
  private pendingChange:       RegimeChange | null = null
  private transitionPlan:      TransitionPlan | null = null
  private regimeHistory:       Array<{ date: Date; regime: string; confidence: number }> = []

  // ── 1. REGIME DETECTION WITH CONFIRMATION ───────────────────────────────

  /**
   * Analyse the market on `date` and apply the 2-period confirmation gate.
   * A regime only switches after CONFIRMATION_PERIODS consecutive signals.
   */
  async detectRegime(date: Date, market: string): Promise<RegimeDecision> {
    let signal: { condition: string; confidence: number }
    try {
      const mc = await analyzeMarketCondition(market, date)
      signal = { condition: mc.condition, confidence: mc.confidence }
    } catch {
      signal = { condition: this.currentRegime, confidence: 50 }
    }

    // Use direct signal — multi-timeframe was too slow and lagging
    const confirmedCondition = signal.condition

    const switched = confirmedCondition !== this.currentRegime

    if (!switched) {
      // Same as current — reset pending change counter
      this.pendingChange = null
      this.recordRegimeHistory(date, this.currentRegime, signal.confidence)
      return {
        regime:       this.currentRegime,
        criteriaType: CRITERIA_MAP[this.currentRegime] ?? 'DELTA',
        switched:     false,
        confidence:   signal.confidence,
      }
    }

    // Signal differs from current regime → accumulate confirmation
    if (this.pendingChange?.newRegime === confirmedCondition) {
      this.pendingChange.confirmationCount++
    } else {
      this.pendingChange = {
        newRegime:         confirmedCondition,
        confirmationCount: 1,
        firstSignalDate:   date,
      }
    }

    if (this.pendingChange.confirmationCount < CONFIRMATION_PERIODS) {
      // Not yet confirmed → stay in current regime
      this.recordRegimeHistory(date, this.currentRegime, signal.confidence)
      return {
        regime:        this.currentRegime,
        criteriaType:  CRITERIA_MAP[this.currentRegime] ?? 'DELTA',
        switched:      false,
        pendingChange: this.pendingChange,
        confidence:    signal.confidence,
      }
    }

    // Confirmed switch
    const fromRegime      = this.currentRegime
    this.currentRegime    = confirmedCondition
    this.pendingChange    = null
    this.recordRegimeHistory(date, this.currentRegime, signal.confidence)

    return {
      regime:       this.currentRegime,
      criteriaType: CRITERIA_MAP[this.currentRegime] ?? 'DELTA',
      switched:     true,
      fromRegime,
      confidence:   signal.confidence,
    }
  }

  // ── 2. MULTI-TIMEFRAME CONFIRMATION ─────────────────────────────────────

  /**
   * Weekly and monthly trend must agree for the signal to be accepted.
   * If they disagree, defer to the monthly (bigger picture).
   *
   * Implementation: use the last 4 weekly signals (last 4 recent history entries)
   * vs the last 3 monthly signals to decide the "higher timeframe" view.
   */
  private async confirmMultiTimeframe(
    dailySignal: string,
    date:        Date,
    market:      string,
  ): Promise<string> {
    try {
      // Weekly: analyse 4 and 2 weeks ago
      const weekAgo4 = new Date(date.getTime() - 28 * 86_400_000)
      const weekAgo2 = new Date(date.getTime() - 14 * 86_400_000)
      const [mc4w, mc2w] = await Promise.all([
        analyzeMarketCondition(market, weekAgo4).catch(() => null),
        analyzeMarketCondition(market, weekAgo2).catch(() => null),
      ])
      const weeklyCondition = mc4w?.condition === mc2w?.condition
        ? (mc4w?.condition ?? dailySignal)
        : dailySignal

      // Monthly: analyse 6 and 3 weeks ago
      const wk6 = new Date(date.getTime() - 42 * 86_400_000)
      const wk3 = new Date(date.getTime() - 21 * 86_400_000)
      const [mc6w, mc3w] = await Promise.all([
        analyzeMarketCondition(market, wk6).catch(() => null),
        analyzeMarketCondition(market, wk3).catch(() => null),
      ])
      const monthlyCondition = mc6w?.condition === mc3w?.condition
        ? (mc6w?.condition ?? dailySignal)
        : dailySignal

      // Both agree → strong confirmation
      if (monthlyCondition === weeklyCondition) return monthlyCondition

      // Disagree → monthly wins (bigger picture)
      return monthlyCondition
    } catch {
      return dailySignal
    }
  }

  // ── 3. SMOOTH TRANSITION PLAN ────────────────────────────────────────────

  /**
   * When a regime switch is confirmed, create a 2-phase rotation plan.
   * Phase 1 (current period): sell worst performers, add 2 new regime stocks.
   * Phase 2 (next period): complete full rotation to new regime.
   */
  buildTransitionPlan(
    fromCriteria:  CriteriaType,
    toCriteria:    CriteriaType,
    switchDate:    Date,
    period:        'WEEKLY' | 'BIWEEKLY' | 'MONTHLY',
  ): TransitionPlan {
    const msPerPeriod = period === 'WEEKLY' ? 7 * 86_400_000 : period === 'BIWEEKLY' ? 15 * 86_400_000 : 30 * 86_400_000
    const plan: TransitionPlan = {
      phase:            1,
      newCriteriaType:  toCriteria,
      fromCriteriaType: fromCriteria,
      maxNewPositions:  2,          // add max 2 new positions in phase 1
      sellThreshold:    40,         // sell any holding scoring < 40 immediately
      transitionDate:   new Date(switchDate.getTime() + msPerPeriod),
    }
    this.transitionPlan = plan
    return plan
  }

  /**
   * Advance the transition plan to phase 2 (or clear it if already complete).
   */
  advanceTransitionPhase(): boolean {
    if (!this.transitionPlan) return false
    if (this.transitionPlan.phase === 1) {
      this.transitionPlan = { ...this.transitionPlan, phase: 2, maxNewPositions: 5 }
      return true   // still in transition
    }
    this.transitionPlan = null
    return false    // transition complete
  }

  // ── 4. MAIN RUN LOOP ─────────────────────────────────────────────────────

  /**
   * Runs the full hybrid backtest using the supplied `rebalanceFn` callback
   * (provided by backtestEngine to avoid circular imports).
   */
  async run(
    config:       BacktestConfig,
    market:       string,
    rebalanceDates: Date[],
    rebalanceFn:  RebalanceFn,
    onProgress?:  (pct: number, date: Date | null, msg: string) => void,
  ): Promise<{ snapshots: PortfolioSnapshot[]; trades: BacktestTrade[] }> {

    // Reset state for this run — initialize regime from actual market condition at start
    this.pendingChange  = null
    this.transitionPlan = null
    this.regimeHistory  = []
    try {
      const initialMC = await analyzeMarketCondition(market, config.startDate)
      this.currentRegime = initialMC.condition ?? 'SIDEWAYS'
    } catch {
      this.currentRegime = 'SIDEWAYS'
    }

    let cash         = config.initialCapital
    let holdings: Holding[]                    = []
    const allTrades:  BacktestTrade[]          = []
    const snapshots:  PortfolioSnapshot[]      = []
    let prevValue     = config.initialCapital

    const total = rebalanceDates.length

    for (let i = 0; i < total; i++) {
      const date = rebalanceDates[i]

      // ── Detect regime (with confirmation + multi-TF) ────────────────────
      const decision = await this.detectRegime(date, market)

      // ── Determine effective criteria for this period ─────────────────────
      let effectiveCriteria: CriteriaType = decision.criteriaType

      if (decision.switched && this.transitionPlan === null) {
        // Build a transition plan on first confirmed switch
        const from = CRITERIA_MAP[decision.fromRegime ?? 'SIDEWAYS'] ?? 'DELTA'
        this.buildTransitionPlan(from, decision.criteriaType, date, config.rebalancePeriod)
      }

      if (this.transitionPlan) {
        if (this.transitionPlan.phase === 1) {
          // Phase 1: still use old criteria for the bulk of the portfolio,
          // but override max positions so only 2 new entries are added
          effectiveCriteria = this.transitionPlan.fromCriteriaType
        } else {
          // Phase 2: fully switch
          effectiveCriteria = this.transitionPlan.newCriteriaType
        }
        this.advanceTransitionPhase()
      }

      // ── Rebalance using selected criteria ────────────────────────────────
      const totalValue = cash + holdings.reduce((s, h) => s + h.value, 0)
      const result = await rebalanceFn(
        holdings, cash, totalValue, date,
        effectiveCriteria, market, config, snapshots,
      )

      holdings = result.holdings
      cash     = result.cash
      allTrades.push(...result.buys, ...result.sells)

      const dailyReturn = prevValue > 0
        ? (result.portfolioValue - prevValue) / prevValue
        : 0
      prevValue = result.portfolioValue

      snapshots.push({
        date,
        portfolioValue:  result.portfolioValue,
        cash,
        holdings,
        criteriaUsed:    effectiveCriteria,
        marketCondition: decision.regime,
        dailyReturn,
      })

      const pct = Math.round(32 + (i / total) * 55)
      onProgress?.(pct, date, `${decision.regime} (${effectiveCriteria}) — ${date.toISOString().slice(0, 10)}`)
    }

    return { snapshots, trades: allTrades }
  }

  // ── 5. REGIME PERFORMANCE ATTRIBUTION ───────────────────────────────────

  trackRegimePerformance(snapshots: PortfolioSnapshot[]): Record<string, RegimeStat> {
    const groups: Record<string, PortfolioSnapshot[]> = {}
    for (const s of snapshots) {
      const key = s.criteriaUsed
      if (!groups[key]) groups[key] = []
      groups[key].push(s)
    }

    const result: Record<string, RegimeStat> = {}
    for (const [regime, snaps] of Object.entries(groups)) {
      const returns  = snaps.map((s) => s.dailyReturn ?? 0)
      const positive = returns.filter((r) => r > 0).length
      const winRate  = returns.length > 0 ? positive / returns.length : 0

      // Cumulative compounded return for this regime
      const contribution = returns.reduce((acc, r) => acc * (1 + r), 1) - 1

      // Max drawdown within regime periods
      let peak = 0, mdd = 0
      for (const s of snaps) {
        if (s.portfolioValue > peak) peak = s.portfolioValue
        const dd = peak > 0 ? (s.portfolioValue - peak) / peak : 0
        if (dd < mdd) mdd = dd
      }

      const avgReturn = returns.length > 0
        ? returns.reduce((a, b) => a + b, 0) / returns.length
        : 0

      result[regime] = {
        avgReturn:     parseFloat((avgReturn * 100).toFixed(4)),
        winRate:       parseFloat((winRate * 100).toFixed(2)),
        maxDrawdown:   parseFloat((mdd * 100).toFixed(2)),
        periodsActive: snaps.length,
        contribution:  parseFloat((contribution * 100).toFixed(2)),
      }
    }
    return result
  }

  // ── 6. TRANSITION COST CALCULATOR ───────────────────────────────────────

  private calcTransitionCosts(
    trades:         BacktestTrade[],
    commissionRate: number = 0.0015,
  ): number {
    // Identify trades that happened in a regime-switch period
    // (approximated as all trades — in a pure single-criteria run there are no "extra" transitions)
    const totalVolume = trades.reduce((s, t) => s + t.value, 0)
    const totalCost   = totalVolume * commissionRate
    const portfolioBase = trades[0]?.value ? trades[0].value * 5 : 1   // rough base
    return portfolioBase > 0 ? parseFloat(((totalCost / portfolioBase) * 100).toFixed(4)) : 0
  }

  // ── 7. HYBRID REPORT GENERATOR ───────────────────────────────────────────

  generateHybridReport(result: BacktestResult): HybridReport {
    const snaps     = result.portfolioHistory
    const byRegime  = this.trackRegimePerformance(snaps)

    // Count confirmed regime switches (adjacent snapshots with different criteriaUsed)
    let switches = 0
    for (let i = 1; i < snaps.length; i++) {
      if (snaps[i].criteriaUsed !== snaps[i - 1].criteriaUsed) switches++
    }

    // Time percentages
    const totalPeriods = snaps.length
    const timeMap: Record<string, string> = {}
    for (const [regime, stat] of Object.entries(byRegime)) {
      const pct = totalPeriods > 0
        ? ((stat.periodsActive / totalPeriods) * 100).toFixed(1)
        : '0.0'
      timeMap[regime] = `${pct}%`
    }

    const transitionCost = this.calcTransitionCosts(result.trades)

    return {
      overall: {
        totalReturn:  result.performance.totalReturn,
        cagr:         result.performance.annualizedReturn,
        sharpe:       result.performance.sharpeRatio,
        maxDrawdown:  result.performance.maxDrawdownPct,
      },
      byRegime,
      regimeSwitches:   switches,
      timeInEachRegime: timeMap,
      transitionCost,
    }
  }

  // ── Helpers ──────────────────────────────────────────────────────────────

  private recordRegimeHistory(date: Date, regime: string, confidence: number): void {
    this.regimeHistory.push({ date, regime, confidence })
    // Keep last 60 entries
    if (this.regimeHistory.length > 60) this.regimeHistory.shift()
  }

  getRegimeHistory(): Array<{ date: Date; regime: string; confidence: number }> {
    return [...this.regimeHistory]
  }

  reset(): void {
    this.currentRegime  = 'SIDEWAYS'
    this.pendingChange  = null
    this.transitionPlan = null
    this.regimeHistory  = []
  }
}

export const hybridBacktestV2 = new HybridBacktestV2()
