# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('app.py', '.'),
        ('backtest_engine.py', '.'),
        ('config.py', '.'),
        ('data_fetcher.py', '.'),
        ('data_model.py', '.'),
        ('disk_cache.py', '.'),
        ('filters.py', '.'),
        ('financial_metrics.py', '.'),
        ('indicators.py', '.'),
        ('institutional_score.py', '.'),
        ('main.py', '.'),
        ('momentum_metrics.py', '.'),
        ('price_provider.py', '.'),
        ('scan_history.py', '.'),
        ('scoring_engine.py', '.'),
        ('symbol_mapper.py', '.'),
        ('technical_signals.py', '.'),
        ('twelve_data_provider.py', '.'),
        ('utils.py', '.'),
        ('watchlist.py', '.'),
        ('yahoo_provider.py', '.'),
        ('rebalance_utils.py', '.'),
        ('.streamlit', '.streamlit'),
        ('data', 'data'),
        ('watchlist.json', '.'),
        ('scan_history.json', '.'),
    ],
    hiddenimports=[
        'streamlit',
        'streamlit.web.cli',
        'streamlit.runtime.scriptrunner.magic_funcs',
        'pyarrow',
        'yfinance',
        'pandas',
        'numpy',
        'requests',
        'dotenv',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Super Investor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Super Investor',
)
app = BUNDLE(
    coll,
    name='Super Investor.app',
    icon=None,
    bundle_identifier='com.superinvestor.app',
)
