// ─── Stock Universe ─────────────────────────────────────────────────────────
// BIST100: 100  BIST100DISI: 503  BISTTUM: 603  US_MARKET: 903
// Source: Super-Investor & BIST config.py  (auto-generated)
// ─────────────────────────────────────────────────────────────────────────────

export type StockSector =
  | 'Financials' | 'Industrials' | 'Materials' | 'Energy'
  | 'Consumer Disc.' | 'Staples' | 'Technology' | 'Healthcare'
  | 'Real Estate' | 'Communication' | 'Utilities';

export interface UniverseStock {
  symbol: string;
  name:   string;
  sector: StockSector;
}

export const BIST100_LIST: UniverseStock[] = [
  { symbol: 'AKBNK', name: 'AKBNK A.Ş.', sector: 'Financials' },
  { symbol: 'AKSEN', name: 'AKSEN A.Ş.', sector: 'Energy' },
  { symbol: 'ALARK', name: 'ALARK A.Ş.', sector: 'Industrials' },
  { symbol: 'ANACM', name: 'ANACM A.Ş.', sector: 'Industrials' },
  { symbol: 'ARCLK', name: 'ARCLK A.Ş.', sector: 'Consumer Disc.' },
  { symbol: 'ASELS', name: 'ASELS A.Ş.', sector: 'Industrials' },
  { symbol: 'AYGAZ', name: 'AYGAZ A.Ş.', sector: 'Energy' },
  { symbol: 'BAGFS', name: 'BAGFS A.Ş.', sector: 'Materials' },
  { symbol: 'BIMAS', name: 'BIMAS A.Ş.', sector: 'Staples' },
  { symbol: 'BRSAN', name: 'BRSAN A.Ş.', sector: 'Materials' },
  { symbol: 'CIMSA', name: 'CIMSA A.Ş.', sector: 'Materials' },
  { symbol: 'DOAS', name: 'DOAS A.Ş.', sector: 'Consumer Disc.' },
  { symbol: 'ECILC', name: 'ECILC A.Ş.', sector: 'Healthcare' },
  { symbol: 'EKGYO', name: 'EKGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'ENKAI', name: 'ENKAI A.Ş.', sector: 'Industrials' },
  { symbol: 'EREGL', name: 'EREGL A.Ş.', sector: 'Materials' },
  { symbol: 'FROTO', name: 'FROTO A.Ş.', sector: 'Consumer Disc.' },
  { symbol: 'GARAN', name: 'GARAN A.Ş.', sector: 'Financials' },
  { symbol: 'GESAN', name: 'GESAN A.Ş.', sector: 'Industrials' },
  { symbol: 'GLYHO', name: 'GLYHO A.Ş.', sector: 'Financials' },
  { symbol: 'GUBRF', name: 'GUBRF A.Ş.', sector: 'Materials' },
  { symbol: 'HALKB', name: 'HALKB A.Ş.', sector: 'Financials' },
  { symbol: 'HEKTS', name: 'HEKTS A.Ş.', sector: 'Materials' },
  { symbol: 'ISCTR', name: 'ISCTR A.Ş.', sector: 'Financials' },
  { symbol: 'ISYAT', name: 'ISYAT A.Ş.', sector: 'Financials' },
  { symbol: 'IZMDC', name: 'IZMDC A.Ş.', sector: 'Materials' },
  { symbol: 'KARTN', name: 'KARTN A.Ş.', sector: 'Materials' },
  { symbol: 'KAYSE', name: 'KAYSE A.Ş.', sector: 'Staples' },
  { symbol: 'KCHOL', name: 'KCHOL A.Ş.', sector: 'Industrials' },
  { symbol: 'KENT', name: 'KENT A.Ş.', sector: 'Staples' },
  { symbol: 'KERVT', name: 'KERVT A.Ş.', sector: 'Staples' },
  { symbol: 'KMPUR', name: 'KMPUR A.Ş.', sector: 'Materials' },
  { symbol: 'KONTR', name: 'KONTR A.Ş.', sector: 'Technology' },
  { symbol: 'KONYA', name: 'KONYA A.Ş.', sector: 'Staples' },
  { symbol: 'KORDS', name: 'KORDS A.Ş.', sector: 'Industrials' },
  { symbol: 'KOZAA', name: 'KOZAA A.Ş.', sector: 'Materials' },
  { symbol: 'KOZAL', name: 'KOZAL A.Ş.', sector: 'Materials' },
  { symbol: 'KRDMD', name: 'KRDMD A.Ş.', sector: 'Materials' },
  { symbol: 'LOGO', name: 'LOGO A.Ş.', sector: 'Technology' },
  { symbol: 'MAVI', name: 'MAVI A.Ş.', sector: 'Consumer Disc.' },
  { symbol: 'MGROS', name: 'MGROS A.Ş.', sector: 'Staples' },
  { symbol: 'NETAS', name: 'NETAS A.Ş.', sector: 'Technology' },
  { symbol: 'ODAS', name: 'ODAS A.Ş.', sector: 'Energy' },
  { symbol: 'OTKAR', name: 'OTKAR A.Ş.', sector: 'Industrials' },
  { symbol: 'OYAKC', name: 'OYAKC A.Ş.', sector: 'Materials' },
  { symbol: 'PETKM', name: 'PETKM A.Ş.', sector: 'Materials' },
  { symbol: 'PGSUS', name: 'PGSUS A.Ş.', sector: 'Industrials' },
  { symbol: 'PRKAB', name: 'PRKAB A.Ş.', sector: 'Industrials' },
  { symbol: 'QUAGR', name: 'QUAGR A.Ş.', sector: 'Materials' },
  { symbol: 'SAFGY', name: 'SAFGY A.Ş.', sector: 'Real Estate' },
  { symbol: 'SAHOL', name: 'SAHOL A.Ş.', sector: 'Industrials' },
  { symbol: 'SASA', name: 'SASA A.Ş.', sector: 'Materials' },
  { symbol: 'SISE', name: 'SISE A.Ş.', sector: 'Materials' },
  { symbol: 'SKBNK', name: 'SKBNK A.Ş.', sector: 'Financials' },
  { symbol: 'SMRTG', name: 'SMRTG A.Ş.', sector: 'Energy' },
  { symbol: 'SODA', name: 'SODA A.Ş.', sector: 'Materials' },
  { symbol: 'SOKM', name: 'SOKM A.Ş.', sector: 'Staples' },
  { symbol: 'TATGD', name: 'TATGD A.Ş.', sector: 'Staples' },
  { symbol: 'TAVHL', name: 'TAVHL A.Ş.', sector: 'Industrials' },
  { symbol: 'TCELL', name: 'TCELL A.Ş.', sector: 'Communication' },
  { symbol: 'THYAO', name: 'THYAO A.Ş.', sector: 'Industrials' },
  { symbol: 'TKFEN', name: 'TKFEN A.Ş.', sector: 'Industrials' },
  { symbol: 'TKNSA', name: 'TKNSA A.Ş.', sector: 'Consumer Disc.' },
  { symbol: 'TOASO', name: 'TOASO A.Ş.', sector: 'Consumer Disc.' },
  { symbol: 'TSKB', name: 'TSKB A.Ş.', sector: 'Financials' },
  { symbol: 'TTKOM', name: 'TTKOM A.Ş.', sector: 'Communication' },
  { symbol: 'TTRAK', name: 'TTRAK A.Ş.', sector: 'Consumer Disc.' },
  { symbol: 'TUPRS', name: 'TUPRS A.Ş.', sector: 'Energy' },
  { symbol: 'TURSG', name: 'TURSG A.Ş.', sector: 'Industrials' },
  { symbol: 'ULKER', name: 'ULKER A.Ş.', sector: 'Staples' },
  { symbol: 'VAKBN', name: 'VAKBN A.Ş.', sector: 'Financials' },
  { symbol: 'VERUS', name: 'VERUS A.Ş.', sector: 'Financials' },
  { symbol: 'VESTL', name: 'VESTL A.Ş.', sector: 'Consumer Disc.' },
  { symbol: 'YKBNK', name: 'YKBNK A.Ş.', sector: 'Financials' },
  { symbol: 'YUNSA', name: 'YUNSA A.Ş.', sector: 'Industrials' },
  { symbol: 'ZOREN', name: 'ZOREN A.Ş.', sector: 'Energy' },
  { symbol: 'AEFES', name: 'AEFES A.Ş.', sector: 'Staples' },
  { symbol: 'ASTOR', name: 'ASTOR A.Ş.', sector: 'Energy' },
  { symbol: 'BFREN', name: 'BFREN A.Ş.', sector: 'Industrials' },
  { symbol: 'BIOEN', name: 'BIOEN A.Ş.', sector: 'Energy' },
  { symbol: 'BRISA', name: 'BRISA A.Ş.', sector: 'Consumer Disc.' },
  { symbol: 'BUCIM', name: 'BUCIM A.Ş.', sector: 'Materials' },
  { symbol: 'CCOLA', name: 'CCOLA A.Ş.', sector: 'Staples' },
  { symbol: 'CELHA', name: 'CELHA A.Ş.', sector: 'Materials' },
  { symbol: 'CEMAS', name: 'CEMAS A.Ş.', sector: 'Materials' },
  { symbol: 'CEMTS', name: 'CEMTS A.Ş.', sector: 'Materials' },
  { symbol: 'CWENE', name: 'CWENE A.Ş.', sector: 'Energy' },
  { symbol: 'DEVA', name: 'DEVA A.Ş.', sector: 'Healthcare' },
  { symbol: 'DOHOL', name: 'DOHOL A.Ş.', sector: 'Industrials' },
  { symbol: 'EGEEN', name: 'EGEEN A.Ş.', sector: 'Industrials' },
  { symbol: 'EGGUB', name: 'EGGUB A.Ş.', sector: 'Materials' },
  { symbol: 'ENJSA', name: 'ENJSA A.Ş.', sector: 'Energy' },
  { symbol: 'ERBOS', name: 'ERBOS A.Ş.', sector: 'Materials' },
  { symbol: 'EUPWR', name: 'EUPWR A.Ş.', sector: 'Energy' },
  { symbol: 'GWIND', name: 'GWIND A.Ş.', sector: 'Energy' },
  { symbol: 'HLGYO', name: 'HLGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'IEYHO', name: 'IEYHO A.Ş.', sector: 'Energy' },
  { symbol: 'INDES', name: 'INDES A.Ş.', sector: 'Technology' },
  { symbol: 'IPEKE', name: 'IPEKE A.Ş.', sector: 'Energy' },
  { symbol: 'ISATR', name: 'ISATR A.Ş.', sector: 'Financials' },
];

export const BIST100DISI_LIST: UniverseStock[] = [
  { symbol: 'A1CAP', name: 'A1CAP A.Ş.', sector: 'Industrials' },
  { symbol: 'A1YEN', name: 'A1YEN A.Ş.', sector: 'Industrials' },
  { symbol: 'ACSEL', name: 'ACSEL A.Ş.', sector: 'Industrials' },
  { symbol: 'ADEL', name: 'ADEL A.Ş.', sector: 'Industrials' },
  { symbol: 'ADESE', name: 'ADESE A.Ş.', sector: 'Industrials' },
  { symbol: 'ADGYO', name: 'ADGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'AFYON', name: 'AFYON A.Ş.', sector: 'Industrials' },
  { symbol: 'AGESA', name: 'AGESA A.Ş.', sector: 'Industrials' },
  { symbol: 'AGHOL', name: 'AGHOL A.Ş.', sector: 'Industrials' },
  { symbol: 'AGROT', name: 'AGROT A.Ş.', sector: 'Industrials' },
  { symbol: 'AGYO', name: 'AGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'AHGAZ', name: 'AHGAZ A.Ş.', sector: 'Industrials' },
  { symbol: 'AHSGY', name: 'AHSGY A.Ş.', sector: 'Real Estate' },
  { symbol: 'AKCNS', name: 'AKCNS A.Ş.', sector: 'Financials' },
  { symbol: 'AKENR', name: 'AKENR A.Ş.', sector: 'Energy' },
  { symbol: 'AKFGY', name: 'AKFGY A.Ş.', sector: 'Real Estate' },
  { symbol: 'AKFIS', name: 'AKFIS A.Ş.', sector: 'Financials' },
  { symbol: 'AKFYE', name: 'AKFYE A.Ş.', sector: 'Financials' },
  { symbol: 'AKGRT', name: 'AKGRT A.Ş.', sector: 'Financials' },
  { symbol: 'AKHAN', name: 'AKHAN A.Ş.', sector: 'Financials' },
  { symbol: 'AKMGY', name: 'AKMGY A.Ş.', sector: 'Real Estate' },
  { symbol: 'AKSA', name: 'AKSA A.Ş.', sector: 'Financials' },
  { symbol: 'AKSGY', name: 'AKSGY A.Ş.', sector: 'Real Estate' },
  { symbol: 'AKSUE', name: 'AKSUE A.Ş.', sector: 'Financials' },
  { symbol: 'AKYHO', name: 'AKYHO A.Ş.', sector: 'Financials' },
  { symbol: 'ALBRK', name: 'ALBRK A.Ş.', sector: 'Financials' },
  { symbol: 'ALCAR', name: 'ALCAR A.Ş.', sector: 'Industrials' },
  { symbol: 'ALCTL', name: 'ALCTL A.Ş.', sector: 'Industrials' },
  { symbol: 'ALFAS', name: 'ALFAS A.Ş.', sector: 'Industrials' },
  { symbol: 'ALGYO', name: 'ALGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'ALKA', name: 'ALKA A.Ş.', sector: 'Industrials' },
  { symbol: 'ALKIM', name: 'ALKIM A.Ş.', sector: 'Industrials' },
  { symbol: 'ALKLC', name: 'ALKLC A.Ş.', sector: 'Industrials' },
  { symbol: 'ALTNY', name: 'ALTNY A.Ş.', sector: 'Industrials' },
  { symbol: 'ALVES', name: 'ALVES A.Ş.', sector: 'Industrials' },
  { symbol: 'ANELE', name: 'ANELE A.Ş.', sector: 'Industrials' },
  { symbol: 'ANGEN', name: 'ANGEN A.Ş.', sector: 'Industrials' },
  { symbol: 'ANHYT', name: 'ANHYT A.Ş.', sector: 'Industrials' },
  { symbol: 'ANSGR', name: 'ANSGR A.Ş.', sector: 'Industrials' },
  { symbol: 'ARASE', name: 'ARASE A.Ş.', sector: 'Industrials' },
  { symbol: 'ARDYZ', name: 'ARDYZ A.Ş.', sector: 'Industrials' },
  { symbol: 'ARENA', name: 'ARENA A.Ş.', sector: 'Industrials' },
  { symbol: 'ARFYE', name: 'ARFYE A.Ş.', sector: 'Industrials' },
  { symbol: 'ARMGD', name: 'ARMGD A.Ş.', sector: 'Industrials' },
  { symbol: 'ARSAN', name: 'ARSAN A.Ş.', sector: 'Industrials' },
  { symbol: 'ARTMS', name: 'ARTMS A.Ş.', sector: 'Technology' },
  { symbol: 'ARZUM', name: 'ARZUM A.Ş.', sector: 'Industrials' },
  { symbol: 'ASGYO', name: 'ASGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'ASUZU', name: 'ASUZU A.Ş.', sector: 'Industrials' },
  { symbol: 'ATAGY', name: 'ATAGY A.Ş.', sector: 'Real Estate' },
  { symbol: 'ATAKP', name: 'ATAKP A.Ş.', sector: 'Industrials' },
  { symbol: 'ATATP', name: 'ATATP A.Ş.', sector: 'Industrials' },
  { symbol: 'ATATR', name: 'ATATR A.Ş.', sector: 'Industrials' },
  { symbol: 'ATEKS', name: 'ATEKS A.Ş.', sector: 'Industrials' },
  { symbol: 'ATLAS', name: 'ATLAS A.Ş.', sector: 'Industrials' },
  { symbol: 'ATSYH', name: 'ATSYH A.Ş.', sector: 'Industrials' },
  { symbol: 'AVGYO', name: 'AVGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'AVHOL', name: 'AVHOL A.Ş.', sector: 'Industrials' },
  { symbol: 'AVOD', name: 'AVOD A.Ş.', sector: 'Industrials' },
  { symbol: 'AVPGY', name: 'AVPGY A.Ş.', sector: 'Real Estate' },
  { symbol: 'AVTUR', name: 'AVTUR A.Ş.', sector: 'Industrials' },
  { symbol: 'AYCES', name: 'AYCES A.Ş.', sector: 'Industrials' },
  { symbol: 'AYDEM', name: 'AYDEM A.Ş.', sector: 'Industrials' },
  { symbol: 'AYEN', name: 'AYEN A.Ş.', sector: 'Industrials' },
  { symbol: 'AYES', name: 'AYES A.Ş.', sector: 'Industrials' },
  { symbol: 'AZTEK', name: 'AZTEK A.Ş.', sector: 'Industrials' },
  { symbol: 'BAHKM', name: 'BAHKM A.Ş.', sector: 'Industrials' },
  { symbol: 'BAKAB', name: 'BAKAB A.Ş.', sector: 'Industrials' },
  { symbol: 'BALAT', name: 'BALAT A.Ş.', sector: 'Industrials' },
  { symbol: 'BALSU', name: 'BALSU A.Ş.', sector: 'Industrials' },
  { symbol: 'BANVT', name: 'BANVT A.Ş.', sector: 'Industrials' },
  { symbol: 'BARMA', name: 'BARMA A.Ş.', sector: 'Industrials' },
  { symbol: 'BASCM', name: 'BASCM A.Ş.', sector: 'Industrials' },
  { symbol: 'BASGZ', name: 'BASGZ A.Ş.', sector: 'Industrials' },
  { symbol: 'BAYRK', name: 'BAYRK A.Ş.', sector: 'Industrials' },
  { symbol: 'BEGYO', name: 'BEGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'BERA', name: 'BERA A.Ş.', sector: 'Industrials' },
  { symbol: 'BESLR', name: 'BESLR A.Ş.', sector: 'Industrials' },
  { symbol: 'BESTE', name: 'BESTE A.Ş.', sector: 'Industrials' },
  { symbol: 'BEYAZ', name: 'BEYAZ A.Ş.', sector: 'Industrials' },
  { symbol: 'BIENY', name: 'BIENY A.Ş.', sector: 'Industrials' },
  { symbol: 'BIGCH', name: 'BIGCH A.Ş.', sector: 'Industrials' },
  { symbol: 'BIGEN', name: 'BIGEN A.Ş.', sector: 'Industrials' },
  { symbol: 'BIGTK', name: 'BIGTK A.Ş.', sector: 'Industrials' },
  { symbol: 'BINBN', name: 'BINBN A.Ş.', sector: 'Industrials' },
  { symbol: 'BINHO', name: 'BINHO A.Ş.', sector: 'Industrials' },
  { symbol: 'BIZIM', name: 'BIZIM A.Ş.', sector: 'Industrials' },
  { symbol: 'BJKAS', name: 'BJKAS A.Ş.', sector: 'Industrials' },
  { symbol: 'BLCYT', name: 'BLCYT A.Ş.', sector: 'Industrials' },
  { symbol: 'BLUME', name: 'BLUME A.Ş.', sector: 'Industrials' },
  { symbol: 'BMSCH', name: 'BMSCH A.Ş.', sector: 'Industrials' },
  { symbol: 'BMSTL', name: 'BMSTL A.Ş.', sector: 'Industrials' },
  { symbol: 'BNTAS', name: 'BNTAS A.Ş.', sector: 'Industrials' },
  { symbol: 'BOBET', name: 'BOBET A.Ş.', sector: 'Industrials' },
  { symbol: 'BORLS', name: 'BORLS A.Ş.', sector: 'Industrials' },
  { symbol: 'BORSK', name: 'BORSK A.Ş.', sector: 'Industrials' },
  { symbol: 'BOSSA', name: 'BOSSA A.Ş.', sector: 'Industrials' },
  { symbol: 'BRKO', name: 'BRKO A.Ş.', sector: 'Industrials' },
  { symbol: 'BRKSN', name: 'BRKSN A.Ş.', sector: 'Industrials' },
  { symbol: 'BRKVY', name: 'BRKVY A.Ş.', sector: 'Industrials' },
  { symbol: 'BRLSM', name: 'BRLSM A.Ş.', sector: 'Industrials' },
  { symbol: 'BRMEN', name: 'BRMEN A.Ş.', sector: 'Industrials' },
  { symbol: 'BRYAT', name: 'BRYAT A.Ş.', sector: 'Industrials' },
  { symbol: 'BSOKE', name: 'BSOKE A.Ş.', sector: 'Industrials' },
  { symbol: 'BTCIM', name: 'BTCIM A.Ş.', sector: 'Industrials' },
  { symbol: 'BULGS', name: 'BULGS A.Ş.', sector: 'Industrials' },
  { symbol: 'BURCE', name: 'BURCE A.Ş.', sector: 'Industrials' },
  { symbol: 'BURVA', name: 'BURVA A.Ş.', sector: 'Industrials' },
  { symbol: 'BVSAN', name: 'BVSAN A.Ş.', sector: 'Industrials' },
  { symbol: 'BYDNR', name: 'BYDNR A.Ş.', sector: 'Industrials' },
  { symbol: 'CANTE', name: 'CANTE A.Ş.', sector: 'Industrials' },
  { symbol: 'CASA', name: 'CASA A.Ş.', sector: 'Industrials' },
  { symbol: 'CATES', name: 'CATES A.Ş.', sector: 'Industrials' },
  { symbol: 'CEMZY', name: 'CEMZY A.Ş.', sector: 'Materials' },
  { symbol: 'CEOEM', name: 'CEOEM A.Ş.', sector: 'Industrials' },
  { symbol: 'CGCAM', name: 'CGCAM A.Ş.', sector: 'Industrials' },
  { symbol: 'CLEBI', name: 'CLEBI A.Ş.', sector: 'Industrials' },
  { symbol: 'CMBTN', name: 'CMBTN A.Ş.', sector: 'Industrials' },
  { symbol: 'CMENT', name: 'CMENT A.Ş.', sector: 'Industrials' },
  { symbol: 'CONSE', name: 'CONSE A.Ş.', sector: 'Industrials' },
  { symbol: 'COSMO', name: 'COSMO A.Ş.', sector: 'Industrials' },
  { symbol: 'CRDFA', name: 'CRDFA A.Ş.', sector: 'Industrials' },
  { symbol: 'CRFSA', name: 'CRFSA A.Ş.', sector: 'Industrials' },
  { symbol: 'CUSAN', name: 'CUSAN A.Ş.', sector: 'Industrials' },
  { symbol: 'CVKMD', name: 'CVKMD A.Ş.', sector: 'Industrials' },
  { symbol: 'DAGI', name: 'DAGI A.Ş.', sector: 'Industrials' },
  { symbol: 'DAPGM', name: 'DAPGM A.Ş.', sector: 'Industrials' },
  { symbol: 'DARDL', name: 'DARDL A.Ş.', sector: 'Industrials' },
  { symbol: 'DCTTR', name: 'DCTTR A.Ş.', sector: 'Industrials' },
  { symbol: 'DENGE', name: 'DENGE A.Ş.', sector: 'Industrials' },
  { symbol: 'DERHL', name: 'DERHL A.Ş.', sector: 'Industrials' },
  { symbol: 'DERIM', name: 'DERIM A.Ş.', sector: 'Industrials' },
  { symbol: 'DESA', name: 'DESA A.Ş.', sector: 'Industrials' },
  { symbol: 'DESPC', name: 'DESPC A.Ş.', sector: 'Industrials' },
  { symbol: 'DGATE', name: 'DGATE A.Ş.', sector: 'Industrials' },
  { symbol: 'DGGYO', name: 'DGGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'DGNMO', name: 'DGNMO A.Ş.', sector: 'Industrials' },
  { symbol: 'DIRIT', name: 'DIRIT A.Ş.', sector: 'Industrials' },
  { symbol: 'DITAS', name: 'DITAS A.Ş.', sector: 'Industrials' },
  { symbol: 'DMRGD', name: 'DMRGD A.Ş.', sector: 'Industrials' },
  { symbol: 'DMSAS', name: 'DMSAS A.Ş.', sector: 'Industrials' },
  { symbol: 'DNISI', name: 'DNISI A.Ş.', sector: 'Industrials' },
  { symbol: 'DOCO', name: 'DOCO A.Ş.', sector: 'Industrials' },
  { symbol: 'DOFER', name: 'DOFER A.Ş.', sector: 'Industrials' },
  { symbol: 'DOFRB', name: 'DOFRB A.Ş.', sector: 'Industrials' },
  { symbol: 'DOGUB', name: 'DOGUB A.Ş.', sector: 'Industrials' },
  { symbol: 'DOKTA', name: 'DOKTA A.Ş.', sector: 'Industrials' },
  { symbol: 'DSTKF', name: 'DSTKF A.Ş.', sector: 'Industrials' },
  { symbol: 'DUNYH', name: 'DUNYH A.Ş.', sector: 'Industrials' },
  { symbol: 'DURDO', name: 'DURDO A.Ş.', sector: 'Industrials' },
  { symbol: 'DURKN', name: 'DURKN A.Ş.', sector: 'Industrials' },
  { symbol: 'DYOBY', name: 'DYOBY A.Ş.', sector: 'Industrials' },
  { symbol: 'DZGYO', name: 'DZGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'EBEBK', name: 'EBEBK A.Ş.', sector: 'Financials' },
  { symbol: 'ECOGR', name: 'ECOGR A.Ş.', sector: 'Industrials' },
  { symbol: 'ECZYT', name: 'ECZYT A.Ş.', sector: 'Healthcare' },
  { symbol: 'EDATA', name: 'EDATA A.Ş.', sector: 'Industrials' },
  { symbol: 'EDIP', name: 'EDIP A.Ş.', sector: 'Industrials' },
  { symbol: 'EFOR', name: 'EFOR A.Ş.', sector: 'Industrials' },
  { symbol: 'EGEGY', name: 'EGEGY A.Ş.', sector: 'Real Estate' },
  { symbol: 'EGEPO', name: 'EGEPO A.Ş.', sector: 'Industrials' },
  { symbol: 'EGPRO', name: 'EGPRO A.Ş.', sector: 'Industrials' },
  { symbol: 'EGSER', name: 'EGSER A.Ş.', sector: 'Industrials' },
  { symbol: 'EKIZ', name: 'EKIZ A.Ş.', sector: 'Industrials' },
  { symbol: 'EKOS', name: 'EKOS A.Ş.', sector: 'Industrials' },
  { symbol: 'EKSUN', name: 'EKSUN A.Ş.', sector: 'Industrials' },
  { symbol: 'ELITE', name: 'ELITE A.Ş.', sector: 'Industrials' },
  { symbol: 'EMKEL', name: 'EMKEL A.Ş.', sector: 'Industrials' },
  { symbol: 'EMNIS', name: 'EMNIS A.Ş.', sector: 'Industrials' },
  { symbol: 'EMPAE', name: 'EMPAE A.Ş.', sector: 'Industrials' },
  { symbol: 'ENDAE', name: 'ENDAE A.Ş.', sector: 'Industrials' },
  { symbol: 'ENERY', name: 'ENERY A.Ş.', sector: 'Industrials' },
  { symbol: 'ENSRI', name: 'ENSRI A.Ş.', sector: 'Industrials' },
  { symbol: 'ENTRA', name: 'ENTRA A.Ş.', sector: 'Industrials' },
  { symbol: 'EPLAS', name: 'EPLAS A.Ş.', sector: 'Industrials' },
  { symbol: 'ERCB', name: 'ERCB A.Ş.', sector: 'Industrials' },
  { symbol: 'ERSU', name: 'ERSU A.Ş.', sector: 'Industrials' },
  { symbol: 'ESCAR', name: 'ESCAR A.Ş.', sector: 'Industrials' },
  { symbol: 'ESCOM', name: 'ESCOM A.Ş.', sector: 'Industrials' },
  { symbol: 'ESEN', name: 'ESEN A.Ş.', sector: 'Industrials' },
  { symbol: 'ETILR', name: 'ETILR A.Ş.', sector: 'Industrials' },
  { symbol: 'ETYAT', name: 'ETYAT A.Ş.', sector: 'Industrials' },
  { symbol: 'EUHOL', name: 'EUHOL A.Ş.', sector: 'Industrials' },
  { symbol: 'EUKYO', name: 'EUKYO A.Ş.', sector: 'Industrials' },
  { symbol: 'EUREN', name: 'EUREN A.Ş.', sector: 'Industrials' },
  { symbol: 'EUYO', name: 'EUYO A.Ş.', sector: 'Industrials' },
  { symbol: 'EYGYO', name: 'EYGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'FADE', name: 'FADE A.Ş.', sector: 'Industrials' },
  { symbol: 'FENER', name: 'FENER A.Ş.', sector: 'Industrials' },
  { symbol: 'FLAP', name: 'FLAP A.Ş.', sector: 'Industrials' },
  { symbol: 'FMIZP', name: 'FMIZP A.Ş.', sector: 'Industrials' },
  { symbol: 'FONET', name: 'FONET A.Ş.', sector: 'Industrials' },
  { symbol: 'FORMT', name: 'FORMT A.Ş.', sector: 'Industrials' },
  { symbol: 'FORTE', name: 'FORTE A.Ş.', sector: 'Industrials' },
  { symbol: 'FRIGO', name: 'FRIGO A.Ş.', sector: 'Industrials' },
  { symbol: 'FRMPL', name: 'FRMPL A.Ş.', sector: 'Industrials' },
  { symbol: 'FZLGY', name: 'FZLGY A.Ş.', sector: 'Real Estate' },
  { symbol: 'GARFA', name: 'GARFA A.Ş.', sector: 'Financials' },
  { symbol: 'GATEG', name: 'GATEG A.Ş.', sector: 'Industrials' },
  { symbol: 'GEDIK', name: 'GEDIK A.Ş.', sector: 'Industrials' },
  { symbol: 'GEDZA', name: 'GEDZA A.Ş.', sector: 'Industrials' },
  { symbol: 'GENIL', name: 'GENIL A.Ş.', sector: 'Industrials' },
  { symbol: 'GENKM', name: 'GENKM A.Ş.', sector: 'Industrials' },
  { symbol: 'GENTS', name: 'GENTS A.Ş.', sector: 'Industrials' },
  { symbol: 'GEREL', name: 'GEREL A.Ş.', sector: 'Industrials' },
  { symbol: 'GIPTA', name: 'GIPTA A.Ş.', sector: 'Industrials' },
  { symbol: 'GLBMD', name: 'GLBMD A.Ş.', sector: 'Healthcare' },
  { symbol: 'GLCVY', name: 'GLCVY A.Ş.', sector: 'Industrials' },
  { symbol: 'GLRMK', name: 'GLRMK A.Ş.', sector: 'Industrials' },
  { symbol: 'GLRYH', name: 'GLRYH A.Ş.', sector: 'Industrials' },
  { symbol: 'GMTAS', name: 'GMTAS A.Ş.', sector: 'Industrials' },
  { symbol: 'GOKNR', name: 'GOKNR A.Ş.', sector: 'Industrials' },
  { symbol: 'GOLTS', name: 'GOLTS A.Ş.', sector: 'Industrials' },
  { symbol: 'GOODY', name: 'GOODY A.Ş.', sector: 'Industrials' },
  { symbol: 'GOZDE', name: 'GOZDE A.Ş.', sector: 'Industrials' },
  { symbol: 'GRNYO', name: 'GRNYO A.Ş.', sector: 'Industrials' },
  { symbol: 'GRSEL', name: 'GRSEL A.Ş.', sector: 'Industrials' },
  { symbol: 'GRTHO', name: 'GRTHO A.Ş.', sector: 'Industrials' },
  { symbol: 'GSDDE', name: 'GSDDE A.Ş.', sector: 'Industrials' },
  { symbol: 'GSDHO', name: 'GSDHO A.Ş.', sector: 'Industrials' },
  { symbol: 'GSRAY', name: 'GSRAY A.Ş.', sector: 'Industrials' },
  { symbol: 'GUNDG', name: 'GUNDG A.Ş.', sector: 'Industrials' },
  { symbol: 'GZNMI', name: 'GZNMI A.Ş.', sector: 'Industrials' },
  { symbol: 'HATEK', name: 'HATEK A.Ş.', sector: 'Industrials' },
  { symbol: 'HATSN', name: 'HATSN A.Ş.', sector: 'Industrials' },
  { symbol: 'HDFGS', name: 'HDFGS A.Ş.', sector: 'Industrials' },
  { symbol: 'HEDEF', name: 'HEDEF A.Ş.', sector: 'Industrials' },
  { symbol: 'HKTM', name: 'HKTM A.Ş.', sector: 'Industrials' },
  { symbol: 'HOROZ', name: 'HOROZ A.Ş.', sector: 'Industrials' },
  { symbol: 'HRKET', name: 'HRKET A.Ş.', sector: 'Industrials' },
  { symbol: 'HTTBT', name: 'HTTBT A.Ş.', sector: 'Industrials' },
  { symbol: 'HUBVC', name: 'HUBVC A.Ş.', sector: 'Industrials' },
  { symbol: 'HUNER', name: 'HUNER A.Ş.', sector: 'Industrials' },
  { symbol: 'HURGZ', name: 'HURGZ A.Ş.', sector: 'Industrials' },
  { symbol: 'ICBCT', name: 'ICBCT A.Ş.', sector: 'Industrials' },
  { symbol: 'ICUGS', name: 'ICUGS A.Ş.', sector: 'Industrials' },
  { symbol: 'IDGYO', name: 'IDGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'IHAAS', name: 'IHAAS A.Ş.', sector: 'Industrials' },
  { symbol: 'IHEVA', name: 'IHEVA A.Ş.', sector: 'Industrials' },
  { symbol: 'IHGZT', name: 'IHGZT A.Ş.', sector: 'Industrials' },
  { symbol: 'IHLAS', name: 'IHLAS A.Ş.', sector: 'Industrials' },
  { symbol: 'IHLGM', name: 'IHLGM A.Ş.', sector: 'Industrials' },
  { symbol: 'IHYAY', name: 'IHYAY A.Ş.', sector: 'Industrials' },
  { symbol: 'IMASM', name: 'IMASM A.Ş.', sector: 'Industrials' },
  { symbol: 'INFO', name: 'INFO A.Ş.', sector: 'Industrials' },
  { symbol: 'INGRM', name: 'INGRM A.Ş.', sector: 'Industrials' },
  { symbol: 'INTEK', name: 'INTEK A.Ş.', sector: 'Industrials' },
  { symbol: 'INTEM', name: 'INTEM A.Ş.', sector: 'Industrials' },
  { symbol: 'INVEO', name: 'INVEO A.Ş.', sector: 'Industrials' },
  { symbol: 'INVES', name: 'INVES A.Ş.', sector: 'Industrials' },
  { symbol: 'ISBIR', name: 'ISBIR A.Ş.', sector: 'Financials' },
  { symbol: 'ISBTR', name: 'ISBTR A.Ş.', sector: 'Financials' },
  { symbol: 'ISDMR', name: 'ISDMR A.Ş.', sector: 'Financials' },
  { symbol: 'ISFIN', name: 'ISFIN A.Ş.', sector: 'Financials' },
  { symbol: 'ISGSY', name: 'ISGSY A.Ş.', sector: 'Financials' },
  { symbol: 'ISGYO', name: 'ISGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'ISKPL', name: 'ISKPL A.Ş.', sector: 'Financials' },
  { symbol: 'ISKUR', name: 'ISKUR A.Ş.', sector: 'Financials' },
  { symbol: 'ISMEN', name: 'ISMEN A.Ş.', sector: 'Financials' },
  { symbol: 'ISSEN', name: 'ISSEN A.Ş.', sector: 'Financials' },
  { symbol: 'IZENR', name: 'IZENR A.Ş.', sector: 'Industrials' },
  { symbol: 'IZFAS', name: 'IZFAS A.Ş.', sector: 'Industrials' },
  { symbol: 'IZINV', name: 'IZINV A.Ş.', sector: 'Industrials' },
  { symbol: 'JANTS', name: 'JANTS A.Ş.', sector: 'Industrials' },
  { symbol: 'KAPLM', name: 'KAPLM A.Ş.', sector: 'Industrials' },
  { symbol: 'KAREL', name: 'KAREL A.Ş.', sector: 'Industrials' },
  { symbol: 'KARSN', name: 'KARSN A.Ş.', sector: 'Industrials' },
  { symbol: 'KATMR', name: 'KATMR A.Ş.', sector: 'Industrials' },
  { symbol: 'KBORU', name: 'KBORU A.Ş.', sector: 'Industrials' },
  { symbol: 'KCAER', name: 'KCAER A.Ş.', sector: 'Industrials' },
  { symbol: 'KERVN', name: 'KERVN A.Ş.', sector: 'Industrials' },
  { symbol: 'KFEIN', name: 'KFEIN A.Ş.', sector: 'Industrials' },
  { symbol: 'KGYO', name: 'KGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'KIMMR', name: 'KIMMR A.Ş.', sector: 'Industrials' },
  { symbol: 'KLGYO', name: 'KLGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'KLKIM', name: 'KLKIM A.Ş.', sector: 'Industrials' },
  { symbol: 'KLMSN', name: 'KLMSN A.Ş.', sector: 'Industrials' },
  { symbol: 'KLNMA', name: 'KLNMA A.Ş.', sector: 'Financials' },
  { symbol: 'KLRHO', name: 'KLRHO A.Ş.', sector: 'Industrials' },
  { symbol: 'KLSER', name: 'KLSER A.Ş.', sector: 'Industrials' },
  { symbol: 'KLSYN', name: 'KLSYN A.Ş.', sector: 'Industrials' },
  { symbol: 'KLYPV', name: 'KLYPV A.Ş.', sector: 'Industrials' },
  { symbol: 'KNFRT', name: 'KNFRT A.Ş.', sector: 'Industrials' },
  { symbol: 'KOCMT', name: 'KOCMT A.Ş.', sector: 'Industrials' },
  { symbol: 'KONKA', name: 'KONKA A.Ş.', sector: 'Staples' },
  { symbol: 'KOPOL', name: 'KOPOL A.Ş.', sector: 'Industrials' },
  { symbol: 'KOTON', name: 'KOTON A.Ş.', sector: 'Industrials' },
  { symbol: 'KRDMA', name: 'KRDMA A.Ş.', sector: 'Industrials' },
  { symbol: 'KRDMB', name: 'KRDMB A.Ş.', sector: 'Industrials' },
  { symbol: 'KRGYO', name: 'KRGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'KRONT', name: 'KRONT A.Ş.', sector: 'Industrials' },
  { symbol: 'KRPLS', name: 'KRPLS A.Ş.', sector: 'Industrials' },
  { symbol: 'KRSTL', name: 'KRSTL A.Ş.', sector: 'Industrials' },
  { symbol: 'KRTEK', name: 'KRTEK A.Ş.', sector: 'Industrials' },
  { symbol: 'KRVGD', name: 'KRVGD A.Ş.', sector: 'Staples' },
  { symbol: 'KSTUR', name: 'KSTUR A.Ş.', sector: 'Industrials' },
  { symbol: 'KTLEV', name: 'KTLEV A.Ş.', sector: 'Industrials' },
  { symbol: 'KTSKR', name: 'KTSKR A.Ş.', sector: 'Industrials' },
  { symbol: 'KUTPO', name: 'KUTPO A.Ş.', sector: 'Industrials' },
  { symbol: 'KUVVA', name: 'KUVVA A.Ş.', sector: 'Industrials' },
  { symbol: 'KUYAS', name: 'KUYAS A.Ş.', sector: 'Industrials' },
  { symbol: 'KZBGY', name: 'KZBGY A.Ş.', sector: 'Real Estate' },
  { symbol: 'KZGYO', name: 'KZGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'LIDER', name: 'LIDER A.Ş.', sector: 'Industrials' },
  { symbol: 'LIDFA', name: 'LIDFA A.Ş.', sector: 'Industrials' },
  { symbol: 'LILAK', name: 'LILAK A.Ş.', sector: 'Industrials' },
  { symbol: 'LINK', name: 'LINK A.Ş.', sector: 'Industrials' },
  { symbol: 'LKMNH', name: 'LKMNH A.Ş.', sector: 'Healthcare' },
  { symbol: 'LMKDC', name: 'LMKDC A.Ş.', sector: 'Industrials' },
  { symbol: 'LRSHO', name: 'LRSHO A.Ş.', sector: 'Industrials' },
  { symbol: 'LUKSK', name: 'LUKSK A.Ş.', sector: 'Industrials' },
  { symbol: 'LXGYO', name: 'LXGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'LYDHO', name: 'LYDHO A.Ş.', sector: 'Industrials' },
  { symbol: 'LYDYE', name: 'LYDYE A.Ş.', sector: 'Industrials' },
  { symbol: 'MAALT', name: 'MAALT A.Ş.', sector: 'Industrials' },
  { symbol: 'MACKO', name: 'MACKO A.Ş.', sector: 'Industrials' },
  { symbol: 'MAGEN', name: 'MAGEN A.Ş.', sector: 'Industrials' },
  { symbol: 'MAKIM', name: 'MAKIM A.Ş.', sector: 'Industrials' },
  { symbol: 'MAKTK', name: 'MAKTK A.Ş.', sector: 'Industrials' },
  { symbol: 'MANAS', name: 'MANAS A.Ş.', sector: 'Industrials' },
  { symbol: 'MARBL', name: 'MARBL A.Ş.', sector: 'Industrials' },
  { symbol: 'MARKA', name: 'MARKA A.Ş.', sector: 'Industrials' },
  { symbol: 'MARMR', name: 'MARMR A.Ş.', sector: 'Industrials' },
  { symbol: 'MARTI', name: 'MARTI A.Ş.', sector: 'Industrials' },
  { symbol: 'MCARD', name: 'MCARD A.Ş.', sector: 'Industrials' },
  { symbol: 'MEDTR', name: 'MEDTR A.Ş.', sector: 'Healthcare' },
  { symbol: 'MEGAP', name: 'MEGAP A.Ş.', sector: 'Industrials' },
  { symbol: 'MEGMT', name: 'MEGMT A.Ş.', sector: 'Industrials' },
  { symbol: 'MEKAG', name: 'MEKAG A.Ş.', sector: 'Industrials' },
  { symbol: 'MEPET', name: 'MEPET A.Ş.', sector: 'Industrials' },
  { symbol: 'MERCN', name: 'MERCN A.Ş.', sector: 'Industrials' },
  { symbol: 'MERIT', name: 'MERIT A.Ş.', sector: 'Industrials' },
  { symbol: 'MERKO', name: 'MERKO A.Ş.', sector: 'Industrials' },
  { symbol: 'METRO', name: 'METRO A.Ş.', sector: 'Industrials' },
  { symbol: 'MEYSU', name: 'MEYSU A.Ş.', sector: 'Industrials' },
  { symbol: 'MHRGY', name: 'MHRGY A.Ş.', sector: 'Real Estate' },
  { symbol: 'MIATK', name: 'MIATK A.Ş.', sector: 'Industrials' },
  { symbol: 'MMCAS', name: 'MMCAS A.Ş.', sector: 'Industrials' },
  { symbol: 'MNDRS', name: 'MNDRS A.Ş.', sector: 'Industrials' },
  { symbol: 'MNDTR', name: 'MNDTR A.Ş.', sector: 'Industrials' },
  { symbol: 'MOBTL', name: 'MOBTL A.Ş.', sector: 'Industrials' },
  { symbol: 'MOGAN', name: 'MOGAN A.Ş.', sector: 'Industrials' },
  { symbol: 'MOPAS', name: 'MOPAS A.Ş.', sector: 'Industrials' },
  { symbol: 'MPARK', name: 'MPARK A.Ş.', sector: 'Industrials' },
  { symbol: 'MRGYO', name: 'MRGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'MRSHL', name: 'MRSHL A.Ş.', sector: 'Industrials' },
  { symbol: 'MSGYO', name: 'MSGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'MTRKS', name: 'MTRKS A.Ş.', sector: 'Industrials' },
  { symbol: 'MTRYO', name: 'MTRYO A.Ş.', sector: 'Industrials' },
  { symbol: 'MZHLD', name: 'MZHLD A.Ş.', sector: 'Industrials' },
  { symbol: 'NATEN', name: 'NATEN A.Ş.', sector: 'Industrials' },
  { symbol: 'NETCD', name: 'NETCD A.Ş.', sector: 'Technology' },
  { symbol: 'NIBAS', name: 'NIBAS A.Ş.', sector: 'Industrials' },
  { symbol: 'NTGAZ', name: 'NTGAZ A.Ş.', sector: 'Industrials' },
  { symbol: 'NTHOL', name: 'NTHOL A.Ş.', sector: 'Industrials' },
  { symbol: 'NUGYO', name: 'NUGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'NUHCM', name: 'NUHCM A.Ş.', sector: 'Materials' },
  { symbol: 'OBAMS', name: 'OBAMS A.Ş.', sector: 'Industrials' },
  { symbol: 'OBASE', name: 'OBASE A.Ş.', sector: 'Industrials' },
  { symbol: 'ODINE', name: 'ODINE A.Ş.', sector: 'Industrials' },
  { symbol: 'OFSYM', name: 'OFSYM A.Ş.', sector: 'Industrials' },
  { symbol: 'ONCSM', name: 'ONCSM A.Ş.', sector: 'Industrials' },
  { symbol: 'ONRYT', name: 'ONRYT A.Ş.', sector: 'Industrials' },
  { symbol: 'ORCAY', name: 'ORCAY A.Ş.', sector: 'Industrials' },
  { symbol: 'ORGE', name: 'ORGE A.Ş.', sector: 'Industrials' },
  { symbol: 'ORMA', name: 'ORMA A.Ş.', sector: 'Industrials' },
  { symbol: 'OSMEN', name: 'OSMEN A.Ş.', sector: 'Industrials' },
  { symbol: 'OSTIM', name: 'OSTIM A.Ş.', sector: 'Industrials' },
  { symbol: 'OTTO', name: 'OTTO A.Ş.', sector: 'Industrials' },
  { symbol: 'OYAYO', name: 'OYAYO A.Ş.', sector: 'Materials' },
  { symbol: 'OYLUM', name: 'OYLUM A.Ş.', sector: 'Industrials' },
  { symbol: 'OYYAT', name: 'OYYAT A.Ş.', sector: 'Industrials' },
  { symbol: 'OZATD', name: 'OZATD A.Ş.', sector: 'Industrials' },
  { symbol: 'OZGYO', name: 'OZGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'OZKGY', name: 'OZKGY A.Ş.', sector: 'Real Estate' },
  { symbol: 'OZRDN', name: 'OZRDN A.Ş.', sector: 'Industrials' },
  { symbol: 'OZSUB', name: 'OZSUB A.Ş.', sector: 'Industrials' },
  { symbol: 'OZYSR', name: 'OZYSR A.Ş.', sector: 'Industrials' },
  { symbol: 'PAGYO', name: 'PAGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'PAHOL', name: 'PAHOL A.Ş.', sector: 'Industrials' },
  { symbol: 'PAMEL', name: 'PAMEL A.Ş.', sector: 'Industrials' },
  { symbol: 'PAPIL', name: 'PAPIL A.Ş.', sector: 'Industrials' },
  { symbol: 'PARSN', name: 'PARSN A.Ş.', sector: 'Industrials' },
  { symbol: 'PASEU', name: 'PASEU A.Ş.', sector: 'Industrials' },
  { symbol: 'PATEK', name: 'PATEK A.Ş.', sector: 'Industrials' },
  { symbol: 'PCILT', name: 'PCILT A.Ş.', sector: 'Industrials' },
  { symbol: 'PEKGY', name: 'PEKGY A.Ş.', sector: 'Real Estate' },
  { symbol: 'PENGD', name: 'PENGD A.Ş.', sector: 'Industrials' },
  { symbol: 'PENTA', name: 'PENTA A.Ş.', sector: 'Industrials' },
  { symbol: 'PETUN', name: 'PETUN A.Ş.', sector: 'Industrials' },
  { symbol: 'PINSU', name: 'PINSU A.Ş.', sector: 'Industrials' },
  { symbol: 'PKART', name: 'PKART A.Ş.', sector: 'Industrials' },
  { symbol: 'PKENT', name: 'PKENT A.Ş.', sector: 'Industrials' },
  { symbol: 'PLTUR', name: 'PLTUR A.Ş.', sector: 'Industrials' },
  { symbol: 'PNLSN', name: 'PNLSN A.Ş.', sector: 'Industrials' },
  { symbol: 'PNSUT', name: 'PNSUT A.Ş.', sector: 'Industrials' },
  { symbol: 'POLHO', name: 'POLHO A.Ş.', sector: 'Industrials' },
  { symbol: 'POLTK', name: 'POLTK A.Ş.', sector: 'Industrials' },
  { symbol: 'PRDGS', name: 'PRDGS A.Ş.', sector: 'Industrials' },
  { symbol: 'PRKME', name: 'PRKME A.Ş.', sector: 'Industrials' },
  { symbol: 'PRZMA', name: 'PRZMA A.Ş.', sector: 'Industrials' },
  { symbol: 'PSDTC', name: 'PSDTC A.Ş.', sector: 'Industrials' },
  { symbol: 'PSGYO', name: 'PSGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'QNBFK', name: 'QNBFK A.Ş.', sector: 'Financials' },
  { symbol: 'QNBTR', name: 'QNBTR A.Ş.', sector: 'Financials' },
  { symbol: 'RALYH', name: 'RALYH A.Ş.', sector: 'Industrials' },
  { symbol: 'RAYSG', name: 'RAYSG A.Ş.', sector: 'Industrials' },
  { symbol: 'REEDR', name: 'REEDR A.Ş.', sector: 'Industrials' },
  { symbol: 'RGYAS', name: 'RGYAS A.Ş.', sector: 'Industrials' },
  { symbol: 'RNPOL', name: 'RNPOL A.Ş.', sector: 'Industrials' },
  { symbol: 'RODRG', name: 'RODRG A.Ş.', sector: 'Industrials' },
  { symbol: 'RTALB', name: 'RTALB A.Ş.', sector: 'Industrials' },
  { symbol: 'RUBNS', name: 'RUBNS A.Ş.', sector: 'Industrials' },
  { symbol: 'RUZYE', name: 'RUZYE A.Ş.', sector: 'Industrials' },
  { symbol: 'RYGYO', name: 'RYGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'RYSAS', name: 'RYSAS A.Ş.', sector: 'Industrials' },
  { symbol: 'SAFKR', name: 'SAFKR A.Ş.', sector: 'Industrials' },
  { symbol: 'SAMAT', name: 'SAMAT A.Ş.', sector: 'Industrials' },
  { symbol: 'SANEL', name: 'SANEL A.Ş.', sector: 'Industrials' },
  { symbol: 'SANFM', name: 'SANFM A.Ş.', sector: 'Industrials' },
  { symbol: 'SANKO', name: 'SANKO A.Ş.', sector: 'Industrials' },
  { symbol: 'SARKY', name: 'SARKY A.Ş.', sector: 'Industrials' },
  { symbol: 'SAYAS', name: 'SAYAS A.Ş.', sector: 'Industrials' },
  { symbol: 'SDTTR', name: 'SDTTR A.Ş.', sector: 'Industrials' },
  { symbol: 'SEGMN', name: 'SEGMN A.Ş.', sector: 'Industrials' },
  { symbol: 'SEGYO', name: 'SEGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'SEKFK', name: 'SEKFK A.Ş.', sector: 'Industrials' },
  { symbol: 'SEKUR', name: 'SEKUR A.Ş.', sector: 'Industrials' },
  { symbol: 'SELEC', name: 'SELEC A.Ş.', sector: 'Industrials' },
  { symbol: 'SELVA', name: 'SELVA A.Ş.', sector: 'Industrials' },
  { symbol: 'SERNT', name: 'SERNT A.Ş.', sector: 'Industrials' },
  { symbol: 'SEYKM', name: 'SEYKM A.Ş.', sector: 'Industrials' },
  { symbol: 'SILVR', name: 'SILVR A.Ş.', sector: 'Industrials' },
  { symbol: 'SKTAS', name: 'SKTAS A.Ş.', sector: 'Industrials' },
  { symbol: 'SKYLP', name: 'SKYLP A.Ş.', sector: 'Industrials' },
  { symbol: 'SKYMD', name: 'SKYMD A.Ş.', sector: 'Industrials' },
  { symbol: 'SMART', name: 'SMART A.Ş.', sector: 'Industrials' },
  { symbol: 'SMRVA', name: 'SMRVA A.Ş.', sector: 'Industrials' },
  { symbol: 'SNGYO', name: 'SNGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'SNICA', name: 'SNICA A.Ş.', sector: 'Industrials' },
  { symbol: 'SNPAM', name: 'SNPAM A.Ş.', sector: 'Industrials' },
  { symbol: 'SODSN', name: 'SODSN A.Ş.', sector: 'Materials' },
  { symbol: 'SOKE', name: 'SOKE A.Ş.', sector: 'Staples' },
  { symbol: 'SONME', name: 'SONME A.Ş.', sector: 'Industrials' },
  { symbol: 'SRVGY', name: 'SRVGY A.Ş.', sector: 'Real Estate' },
  { symbol: 'SUMAS', name: 'SUMAS A.Ş.', sector: 'Industrials' },
  { symbol: 'SUNTK', name: 'SUNTK A.Ş.', sector: 'Industrials' },
  { symbol: 'SURGY', name: 'SURGY A.Ş.', sector: 'Real Estate' },
  { symbol: 'SUWEN', name: 'SUWEN A.Ş.', sector: 'Industrials' },
  { symbol: 'SVGYO', name: 'SVGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'TABGD', name: 'TABGD A.Ş.', sector: 'Industrials' },
  { symbol: 'TARKM', name: 'TARKM A.Ş.', sector: 'Industrials' },
  { symbol: 'TATEN', name: 'TATEN A.Ş.', sector: 'Staples' },
  { symbol: 'TBORG', name: 'TBORG A.Ş.', sector: 'Industrials' },
  { symbol: 'TCKRC', name: 'TCKRC A.Ş.', sector: 'Communication' },
  { symbol: 'TDGYO', name: 'TDGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'TEHOL', name: 'TEHOL A.Ş.', sector: 'Industrials' },
  { symbol: 'TEKTU', name: 'TEKTU A.Ş.', sector: 'Industrials' },
  { symbol: 'TERA', name: 'TERA A.Ş.', sector: 'Industrials' },
  { symbol: 'TEZOL', name: 'TEZOL A.Ş.', sector: 'Industrials' },
  { symbol: 'TGSAS', name: 'TGSAS A.Ş.', sector: 'Industrials' },
  { symbol: 'TLMAN', name: 'TLMAN A.Ş.', sector: 'Healthcare' },
  { symbol: 'TMPOL', name: 'TMPOL A.Ş.', sector: 'Industrials' },
  { symbol: 'TMSN', name: 'TMSN A.Ş.', sector: 'Industrials' },
  { symbol: 'TNZTP', name: 'TNZTP A.Ş.', sector: 'Industrials' },
  { symbol: 'TRALT', name: 'TRALT A.Ş.', sector: 'Industrials' },
  { symbol: 'TRCAS', name: 'TRCAS A.Ş.', sector: 'Energy' },
  { symbol: 'TRENJ', name: 'TRENJ A.Ş.', sector: 'Industrials' },
  { symbol: 'TRGYO', name: 'TRGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'TRHOL', name: 'TRHOL A.Ş.', sector: 'Industrials' },
  { symbol: 'TRILC', name: 'TRILC A.Ş.', sector: 'Industrials' },
  { symbol: 'TRMET', name: 'TRMET A.Ş.', sector: 'Industrials' },
  { symbol: 'TSGYO', name: 'TSGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'TSPOR', name: 'TSPOR A.Ş.', sector: 'Industrials' },
  { symbol: 'TUCLK', name: 'TUCLK A.Ş.', sector: 'Industrials' },
  { symbol: 'TUKAS', name: 'TUKAS A.Ş.', sector: 'Industrials' },
  { symbol: 'TUREX', name: 'TUREX A.Ş.', sector: 'Industrials' },
  { symbol: 'TURGG', name: 'TURGG A.Ş.', sector: 'Industrials' },
  { symbol: 'UCAYM', name: 'UCAYM A.Ş.', sector: 'Industrials' },
  { symbol: 'UFUK', name: 'UFUK A.Ş.', sector: 'Industrials' },
  { symbol: 'ULAS', name: 'ULAS A.Ş.', sector: 'Industrials' },
  { symbol: 'ULUFA', name: 'ULUFA A.Ş.', sector: 'Industrials' },
  { symbol: 'ULUSE', name: 'ULUSE A.Ş.', sector: 'Industrials' },
  { symbol: 'ULUUN', name: 'ULUUN A.Ş.', sector: 'Industrials' },
  { symbol: 'UMPAS', name: 'UMPAS A.Ş.', sector: 'Industrials' },
  { symbol: 'UNLU', name: 'UNLU A.Ş.', sector: 'Industrials' },
  { symbol: 'USAK', name: 'USAK A.Ş.', sector: 'Industrials' },
  { symbol: 'VAKFA', name: 'VAKFA A.Ş.', sector: 'Industrials' },
  { symbol: 'VAKFN', name: 'VAKFN A.Ş.', sector: 'Industrials' },
  { symbol: 'VAKKO', name: 'VAKKO A.Ş.', sector: 'Industrials' },
  { symbol: 'VANGD', name: 'VANGD A.Ş.', sector: 'Industrials' },
  { symbol: 'VBTYZ', name: 'VBTYZ A.Ş.', sector: 'Technology' },
  { symbol: 'VERTU', name: 'VERTU A.Ş.', sector: 'Industrials' },
  { symbol: 'VESBE', name: 'VESBE A.Ş.', sector: 'Industrials' },
  { symbol: 'VKFYO', name: 'VKFYO A.Ş.', sector: 'Financials' },
  { symbol: 'VKGYO', name: 'VKGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'VKING', name: 'VKING A.Ş.', sector: 'Financials' },
  { symbol: 'VRGYO', name: 'VRGYO A.Ş.', sector: 'Real Estate' },
  { symbol: 'VSNMD', name: 'VSNMD A.Ş.', sector: 'Industrials' },
  { symbol: 'YAPRK', name: 'YAPRK A.Ş.', sector: 'Industrials' },
  { symbol: 'YATAS', name: 'YATAS A.Ş.', sector: 'Industrials' },
  { symbol: 'YAYLA', name: 'YAYLA A.Ş.', sector: 'Industrials' },
  { symbol: 'YBTAS', name: 'YBTAS A.Ş.', sector: 'Industrials' },
];

// Combined BIST100 + BIST100DISI = 603
export const BISTTUM_LIST: UniverseStock[] = [
  ...BIST100_LIST,
  ...BIST100DISI_LIST,
];

export const US_MARKET_LIST: UniverseStock[] = [
  { symbol: 'A', name: 'A Inc.', sector: 'Industrials' },
  { symbol: 'AA', name: 'AA Inc.', sector: 'Industrials' },
  { symbol: 'AAL', name: 'AAL Inc.', sector: 'Industrials' },
  { symbol: 'AAON', name: 'AAON Inc.', sector: 'Industrials' },
  { symbol: 'AAPL', name: 'Apple', sector: 'Technology' },
  { symbol: 'ABBV', name: 'AbbVie', sector: 'Healthcare' },
  { symbol: 'ABNB', name: 'Airbnb', sector: 'Consumer Disc.' },
  { symbol: 'ABT', name: 'ABT Inc.', sector: 'Healthcare' },
  { symbol: 'ACGL', name: 'ACGL Inc.', sector: 'Industrials' },
  { symbol: 'ACI', name: 'ACI Inc.', sector: 'Industrials' },
  { symbol: 'ACM', name: 'ACM Inc.', sector: 'Industrials' },
  { symbol: 'ACN', name: 'Accenture', sector: 'Industrials' },
  { symbol: 'ADBE', name: 'Adobe', sector: 'Technology' },
  { symbol: 'ADC', name: 'ADC Inc.', sector: 'Industrials' },
  { symbol: 'ADI', name: 'ADI Inc.', sector: 'Technology' },
  { symbol: 'ADM', name: 'ADM Inc.', sector: 'Industrials' },
  { symbol: 'ADP', name: 'ADP Inc.', sector: 'Industrials' },
  { symbol: 'ADSK', name: 'ADSK Inc.', sector: 'Industrials' },
  { symbol: 'AEE', name: 'AEE Inc.', sector: 'Industrials' },
  { symbol: 'AEIS', name: 'AEIS Inc.', sector: 'Industrials' },
  { symbol: 'AEP', name: 'AEP Inc.', sector: 'Utilities' },
  { symbol: 'AES', name: 'AES Inc.', sector: 'Industrials' },
  { symbol: 'AFG', name: 'AFG Inc.', sector: 'Industrials' },
  { symbol: 'AFL', name: 'AFL Inc.', sector: 'Industrials' },
  { symbol: 'AGCO', name: 'AGCO Inc.', sector: 'Industrials' },
  { symbol: 'AHR', name: 'AHR Inc.', sector: 'Industrials' },
  { symbol: 'AIG', name: 'AIG Inc.', sector: 'Industrials' },
  { symbol: 'AIT', name: 'AIT Inc.', sector: 'Industrials' },
  { symbol: 'AIZ', name: 'AIZ Inc.', sector: 'Industrials' },
  { symbol: 'AJG', name: 'AJG Inc.', sector: 'Industrials' },
  { symbol: 'AKAM', name: 'AKAM Inc.', sector: 'Technology' },
  { symbol: 'ALB', name: 'ALB Inc.', sector: 'Industrials' },
  { symbol: 'ALGM', name: 'ALGM Inc.', sector: 'Industrials' },
  { symbol: 'ALGN', name: 'ALGN Inc.', sector: 'Industrials' },
  { symbol: 'ALK', name: 'ALK Inc.', sector: 'Industrials' },
  { symbol: 'ALL', name: 'ALL Inc.', sector: 'Industrials' },
  { symbol: 'ALLE', name: 'ALLE Inc.', sector: 'Industrials' },
  { symbol: 'ALLY', name: 'ALLY Inc.', sector: 'Industrials' },
  { symbol: 'ALV', name: 'ALV Inc.', sector: 'Industrials' },
  { symbol: 'AM', name: 'AM Inc.', sector: 'Industrials' },
  { symbol: 'AMAT', name: 'Applied Materials', sector: 'Technology' },
  { symbol: 'AMCR', name: 'AMCR Inc.', sector: 'Industrials' },
  { symbol: 'AMD', name: 'AMD', sector: 'Technology' },
  { symbol: 'AME', name: 'AME Inc.', sector: 'Industrials' },
  { symbol: 'AMG', name: 'AMG Inc.', sector: 'Industrials' },
  { symbol: 'AMGN', name: 'Amgen', sector: 'Healthcare' },
  { symbol: 'AMH', name: 'AMH Inc.', sector: 'Industrials' },
  { symbol: 'AMKR', name: 'AMKR Inc.', sector: 'Industrials' },
  { symbol: 'AMP', name: 'AMP Inc.', sector: 'Industrials' },
  { symbol: 'AMT', name: 'AMT Inc.', sector: 'Real Estate' },
  { symbol: 'AMZN', name: 'Amazon', sector: 'Consumer Disc.' },
  { symbol: 'AN', name: 'AN Inc.', sector: 'Industrials' },
  { symbol: 'ANET', name: 'ANET Inc.', sector: 'Industrials' },
  { symbol: 'ANF', name: 'ANF Inc.', sector: 'Industrials' },
  { symbol: 'AON', name: 'AON Inc.', sector: 'Industrials' },
  { symbol: 'AOS', name: 'AOS Inc.', sector: 'Industrials' },
  { symbol: 'APA', name: 'APA Inc.', sector: 'Industrials' },
  { symbol: 'APD', name: 'APD Inc.', sector: 'Materials' },
  { symbol: 'APG', name: 'APG Inc.', sector: 'Industrials' },
  { symbol: 'APH', name: 'APH Inc.', sector: 'Industrials' },
  { symbol: 'APO', name: 'APO Inc.', sector: 'Industrials' },
  { symbol: 'APP', name: 'APP Inc.', sector: 'Industrials' },
  { symbol: 'APPF', name: 'APPF Inc.', sector: 'Industrials' },
  { symbol: 'APTV', name: 'APTV Inc.', sector: 'Industrials' },
  { symbol: 'AR', name: 'AR Inc.', sector: 'Industrials' },
  { symbol: 'ARE', name: 'ARE Inc.', sector: 'Industrials' },
  { symbol: 'ARES', name: 'ARES Inc.', sector: 'Industrials' },
  { symbol: 'ARMK', name: 'ARMK Inc.', sector: 'Industrials' },
  { symbol: 'ARW', name: 'ARW Inc.', sector: 'Industrials' },
  { symbol: 'ARWR', name: 'ARWR Inc.', sector: 'Industrials' },
  { symbol: 'ASB', name: 'ASB Inc.', sector: 'Industrials' },
  { symbol: 'ASH', name: 'ASH Inc.', sector: 'Industrials' },
  { symbol: 'ATI', name: 'ATI Inc.', sector: 'Industrials' },
  { symbol: 'ATO', name: 'ATO Inc.', sector: 'Industrials' },
  { symbol: 'ATR', name: 'ATR Inc.', sector: 'Industrials' },
  { symbol: 'AVAV', name: 'AVAV Inc.', sector: 'Industrials' },
  { symbol: 'AVB', name: 'AVB Inc.', sector: 'Industrials' },
  { symbol: 'AVGO', name: 'Broadcom', sector: 'Technology' },
  { symbol: 'AVNT', name: 'AVNT Inc.', sector: 'Industrials' },
  { symbol: 'AVT', name: 'AVT Inc.', sector: 'Industrials' },
  { symbol: 'AVTR', name: 'AVTR Inc.', sector: 'Industrials' },
  { symbol: 'AVY', name: 'AVY Inc.', sector: 'Industrials' },
  { symbol: 'AWK', name: 'AWK Inc.', sector: 'Industrials' },
  { symbol: 'AXON', name: 'AXON Inc.', sector: 'Industrials' },
  { symbol: 'AXP', name: 'AXP Inc.', sector: 'Financials' },
  { symbol: 'AXTA', name: 'AXTA Inc.', sector: 'Industrials' },
  { symbol: 'AYI', name: 'AYI Inc.', sector: 'Industrials' },
  { symbol: 'AZO', name: 'AZO Inc.', sector: 'Industrials' },
  { symbol: 'BA', name: 'Boeing', sector: 'Industrials' },
  { symbol: 'BAC', name: 'Bank of America', sector: 'Financials' },
  { symbol: 'BAH', name: 'BAH Inc.', sector: 'Industrials' },
  { symbol: 'BALL', name: 'BALL Inc.', sector: 'Industrials' },
  { symbol: 'BAX', name: 'BAX Inc.', sector: 'Industrials' },
  { symbol: 'BBWI', name: 'BBWI Inc.', sector: 'Industrials' },
  { symbol: 'BBY', name: 'BBY Inc.', sector: 'Industrials' },
  { symbol: 'BC', name: 'BC Inc.', sector: 'Industrials' },
  { symbol: 'BCO', name: 'BCO Inc.', sector: 'Industrials' },
  { symbol: 'BDC', name: 'BDC Inc.', sector: 'Industrials' },
  { symbol: 'BDX', name: 'BDX Inc.', sector: 'Industrials' },
  { symbol: 'BEN', name: 'BEN Inc.', sector: 'Industrials' },
  { symbol: 'BF.B', name: 'BF.B Inc.', sector: 'Industrials' },
  { symbol: 'BG', name: 'BG Inc.', sector: 'Industrials' },
  { symbol: 'BHF', name: 'BHF Inc.', sector: 'Industrials' },
  { symbol: 'BIIB', name: 'BIIB Inc.', sector: 'Healthcare' },
  { symbol: 'BILL', name: 'BILL Inc.', sector: 'Industrials' },
  { symbol: 'BIO', name: 'BIO Inc.', sector: 'Industrials' },
  { symbol: 'BJ', name: 'BJ Inc.', sector: 'Industrials' },
  { symbol: 'BK', name: 'BK Inc.', sector: 'Industrials' },
  { symbol: 'BKH', name: 'BKH Inc.', sector: 'Industrials' },
  { symbol: 'BKNG', name: 'BKNG Inc.', sector: 'Consumer Disc.' },
  { symbol: 'BKR', name: 'BKR Inc.', sector: 'Energy' },
  { symbol: 'BLD', name: 'BLD Inc.', sector: 'Industrials' },
  { symbol: 'BLDR', name: 'BLDR Inc.', sector: 'Industrials' },
  { symbol: 'BLK', name: 'BlackRock', sector: 'Financials' },
  { symbol: 'BLKB', name: 'BLKB Inc.', sector: 'Industrials' },
  { symbol: 'BMRN', name: 'BMRN Inc.', sector: 'Industrials' },
  { symbol: 'BMY', name: 'Bristol-Myers', sector: 'Healthcare' },
  { symbol: 'BR', name: 'BR Inc.', sector: 'Industrials' },
  { symbol: 'BRBR', name: 'BRBR Inc.', sector: 'Industrials' },
  { symbol: 'BRK.B', name: 'BRK.B Inc.', sector: 'Industrials' },
  { symbol: 'BRKR', name: 'BRKR Inc.', sector: 'Industrials' },
  { symbol: 'BRO', name: 'BRO Inc.', sector: 'Industrials' },
  { symbol: 'BROS', name: 'BROS Inc.', sector: 'Industrials' },
  { symbol: 'BRX', name: 'BRX Inc.', sector: 'Industrials' },
  { symbol: 'BSX', name: 'BSX Inc.', sector: 'Industrials' },
  { symbol: 'BSY', name: 'BSY Inc.', sector: 'Industrials' },
  { symbol: 'BURL', name: 'BURL Inc.', sector: 'Industrials' },
  { symbol: 'BWA', name: 'BWA Inc.', sector: 'Industrials' },
  { symbol: 'BWXT', name: 'BWXT Inc.', sector: 'Industrials' },
  { symbol: 'BX', name: 'BX Inc.', sector: 'Industrials' },
  { symbol: 'BXP', name: 'BXP Inc.', sector: 'Industrials' },
  { symbol: 'BYD', name: 'BYD Inc.', sector: 'Industrials' },
  { symbol: 'C', name: 'C Inc.', sector: 'Financials' },
  { symbol: 'CACI', name: 'CACI Inc.', sector: 'Industrials' },
  { symbol: 'CAG', name: 'CAG Inc.', sector: 'Industrials' },
  { symbol: 'CAH', name: 'CAH Inc.', sector: 'Industrials' },
  { symbol: 'CAR', name: 'CAR Inc.', sector: 'Industrials' },
  { symbol: 'CARR', name: 'CARR Inc.', sector: 'Industrials' },
  { symbol: 'CART', name: 'CART Inc.', sector: 'Industrials' },
  { symbol: 'CASY', name: 'CASY Inc.', sector: 'Industrials' },
  { symbol: 'CAT', name: 'Caterpillar', sector: 'Industrials' },
  { symbol: 'CAVA', name: 'CAVA Inc.', sector: 'Industrials' },
  { symbol: 'CB', name: 'CB Inc.', sector: 'Industrials' },
  { symbol: 'CBOE', name: 'CBOE Inc.', sector: 'Industrials' },
  { symbol: 'CBRE', name: 'CBRE Inc.', sector: 'Industrials' },
  { symbol: 'CBSH', name: 'CBSH Inc.', sector: 'Industrials' },
  { symbol: 'CBT', name: 'CBT Inc.', sector: 'Industrials' },
  { symbol: 'CCI', name: 'CCI Inc.', sector: 'Real Estate' },
  { symbol: 'CCK', name: 'CCK Inc.', sector: 'Industrials' },
  { symbol: 'CCL', name: 'CCL Inc.', sector: 'Industrials' },
  { symbol: 'CDNS', name: 'CDNS Inc.', sector: 'Technology' },
  { symbol: 'CDP', name: 'CDP Inc.', sector: 'Industrials' },
  { symbol: 'CDW', name: 'CDW Inc.', sector: 'Industrials' },
  { symbol: 'CEG', name: 'CEG Inc.', sector: 'Industrials' },
  { symbol: 'CELH', name: 'CELH Inc.', sector: 'Industrials' },
  { symbol: 'CF', name: 'CF Inc.', sector: 'Materials' },
  { symbol: 'CFG', name: 'CFG Inc.', sector: 'Industrials' },
  { symbol: 'CFR', name: 'CFR Inc.', sector: 'Industrials' },
  { symbol: 'CG', name: 'CG Inc.', sector: 'Industrials' },
  { symbol: 'CGNX', name: 'CGNX Inc.', sector: 'Industrials' },
  { symbol: 'CHD', name: 'CHD Inc.', sector: 'Industrials' },
  { symbol: 'CHDN', name: 'CHDN Inc.', sector: 'Industrials' },
  { symbol: 'CHE', name: 'CHE Inc.', sector: 'Industrials' },
  { symbol: 'CHH', name: 'CHH Inc.', sector: 'Industrials' },
  { symbol: 'CHRD', name: 'CHRD Inc.', sector: 'Industrials' },
  { symbol: 'CHRW', name: 'CHRW Inc.', sector: 'Industrials' },
  { symbol: 'CHTR', name: 'CHTR Inc.', sector: 'Communication' },
  { symbol: 'CHWY', name: 'CHWY Inc.', sector: 'Industrials' },
  { symbol: 'CI', name: 'CI Inc.', sector: 'Industrials' },
  { symbol: 'CIEN', name: 'CIEN Inc.', sector: 'Industrials' },
  { symbol: 'CINF', name: 'CINF Inc.', sector: 'Industrials' },
  { symbol: 'CL', name: 'CL Inc.', sector: 'Staples' },
  { symbol: 'CLF', name: 'CLF Inc.', sector: 'Industrials' },
  { symbol: 'CLH', name: 'CLH Inc.', sector: 'Industrials' },
  { symbol: 'CLX', name: 'CLX Inc.', sector: 'Industrials' },
  { symbol: 'CMC', name: 'CMC Inc.', sector: 'Industrials' },
  { symbol: 'CMCSA', name: 'Comcast', sector: 'Communication' },
  { symbol: 'CME', name: 'CME Inc.', sector: 'Industrials' },
  { symbol: 'CMG', name: 'CMG Inc.', sector: 'Consumer Disc.' },
  { symbol: 'CMI', name: 'CMI Inc.', sector: 'Industrials' },
  { symbol: 'CMS', name: 'CMS Inc.', sector: 'Industrials' },
  { symbol: 'CNC', name: 'CNC Inc.', sector: 'Industrials' },
  { symbol: 'CNH', name: 'CNH Inc.', sector: 'Industrials' },
  { symbol: 'CNM', name: 'CNM Inc.', sector: 'Industrials' },
  { symbol: 'CNO', name: 'CNO Inc.', sector: 'Industrials' },
  { symbol: 'CNP', name: 'CNP Inc.', sector: 'Industrials' },
  { symbol: 'CNX', name: 'CNX Inc.', sector: 'Industrials' },
  { symbol: 'CNXC', name: 'CNXC Inc.', sector: 'Industrials' },
  { symbol: 'COF', name: 'COF Inc.', sector: 'Financials' },
  { symbol: 'COHR', name: 'COHR Inc.', sector: 'Industrials' },
  { symbol: 'COIN', name: 'COIN Inc.', sector: 'Industrials' },
  { symbol: 'COKE', name: 'COKE Inc.', sector: 'Industrials' },
  { symbol: 'COLB', name: 'COLB Inc.', sector: 'Industrials' },
  { symbol: 'COLM', name: 'COLM Inc.', sector: 'Industrials' },
  { symbol: 'COO', name: 'COO Inc.', sector: 'Industrials' },
  { symbol: 'COP', name: 'COP Inc.', sector: 'Energy' },
  { symbol: 'COR', name: 'COR Inc.', sector: 'Industrials' },
  { symbol: 'COST', name: 'Costco', sector: 'Staples' },
  { symbol: 'COTY', name: 'COTY Inc.', sector: 'Industrials' },
  { symbol: 'CPAY', name: 'CPAY Inc.', sector: 'Industrials' },
  { symbol: 'CPB', name: 'CPB Inc.', sector: 'Industrials' },
  { symbol: 'CPRI', name: 'CPRI Inc.', sector: 'Industrials' },
  { symbol: 'CPRT', name: 'CPRT Inc.', sector: 'Industrials' },
  { symbol: 'CPT', name: 'CPT Inc.', sector: 'Industrials' },
  { symbol: 'CR', name: 'CR Inc.', sector: 'Industrials' },
  { symbol: 'CRBG', name: 'CRBG Inc.', sector: 'Industrials' },
  { symbol: 'CRH', name: 'CRH Inc.', sector: 'Industrials' },
  { symbol: 'CRL', name: 'CRL Inc.', sector: 'Industrials' },
  { symbol: 'CRM', name: 'Salesforce', sector: 'Technology' },
  { symbol: 'CROX', name: 'CROX Inc.', sector: 'Industrials' },
  { symbol: 'CRS', name: 'CRS Inc.', sector: 'Industrials' },
  { symbol: 'CRUS', name: 'CRUS Inc.', sector: 'Industrials' },
  { symbol: 'CRWD', name: 'CrowdStrike', sector: 'Technology' },
  { symbol: 'CSCO', name: 'Cisco', sector: 'Industrials' },
  { symbol: 'CSGP', name: 'CSGP Inc.', sector: 'Industrials' },
  { symbol: 'CSL', name: 'CSL Inc.', sector: 'Industrials' },
  { symbol: 'CSX', name: 'CSX Inc.', sector: 'Industrials' },
  { symbol: 'CTAS', name: 'CTAS Inc.', sector: 'Industrials' },
  { symbol: 'CTRA', name: 'CTRA Inc.', sector: 'Industrials' },
  { symbol: 'CTRE', name: 'CTRE Inc.', sector: 'Industrials' },
  { symbol: 'CTSH', name: 'CTSH Inc.', sector: 'Industrials' },
  { symbol: 'CTVA', name: 'CTVA Inc.', sector: 'Industrials' },
  { symbol: 'CUBE', name: 'CUBE Inc.', sector: 'Industrials' },
  { symbol: 'CUZ', name: 'CUZ Inc.', sector: 'Industrials' },
  { symbol: 'CVLT', name: 'CVLT Inc.', sector: 'Industrials' },
  { symbol: 'CVNA', name: 'CVNA Inc.', sector: 'Industrials' },
  { symbol: 'CVS', name: 'CVS Inc.', sector: 'Industrials' },
  { symbol: 'CVX', name: 'Chevron', sector: 'Energy' },
  { symbol: 'CW', name: 'CW Inc.', sector: 'Industrials' },
  { symbol: 'CXT', name: 'CXT Inc.', sector: 'Industrials' },
  { symbol: 'CYTK', name: 'CYTK Inc.', sector: 'Industrials' },
  { symbol: 'D', name: 'D Inc.', sector: 'Utilities' },
  { symbol: 'DAL', name: 'DAL Inc.', sector: 'Industrials' },
  { symbol: 'DAR', name: 'DAR Inc.', sector: 'Industrials' },
  { symbol: 'DASH', name: 'DASH Inc.', sector: 'Industrials' },
  { symbol: 'DBX', name: 'DBX Inc.', sector: 'Industrials' },
  { symbol: 'DCI', name: 'DCI Inc.', sector: 'Industrials' },
  { symbol: 'DD', name: 'DD Inc.', sector: 'Industrials' },
  { symbol: 'DDOG', name: 'DDOG Inc.', sector: 'Technology' },
  { symbol: 'DE', name: 'DE Inc.', sector: 'Industrials' },
  { symbol: 'DECK', name: 'DECK Inc.', sector: 'Industrials' },
  { symbol: 'DELL', name: 'DELL Inc.', sector: 'Industrials' },
  { symbol: 'DG', name: 'DG Inc.', sector: 'Industrials' },
  { symbol: 'DGX', name: 'DGX Inc.', sector: 'Industrials' },
  { symbol: 'DHI', name: 'DHI Inc.', sector: 'Industrials' },
  { symbol: 'DHR', name: 'DHR Inc.', sector: 'Industrials' },
  { symbol: 'DINO', name: 'DINO Inc.', sector: 'Industrials' },
  { symbol: 'DIS', name: 'Disney', sector: 'Communication' },
  { symbol: 'DKS', name: 'DKS Inc.', sector: 'Industrials' },
  { symbol: 'DLB', name: 'DLB Inc.', sector: 'Industrials' },
  { symbol: 'DLR', name: 'DLR Inc.', sector: 'Real Estate' },
  { symbol: 'DLTR', name: 'DLTR Inc.', sector: 'Industrials' },
  { symbol: 'DOC', name: 'DOC Inc.', sector: 'Industrials' },
  { symbol: 'DOCS', name: 'DOCS Inc.', sector: 'Industrials' },
  { symbol: 'DOCU', name: 'DOCU Inc.', sector: 'Industrials' },
  { symbol: 'DOV', name: 'DOV Inc.', sector: 'Industrials' },
  { symbol: 'DOW', name: 'DOW Inc.', sector: 'Industrials' },
  { symbol: 'DPZ', name: 'DPZ Inc.', sector: 'Industrials' },
  { symbol: 'DRI', name: 'DRI Inc.', sector: 'Industrials' },
  { symbol: 'DT', name: 'DT Inc.', sector: 'Industrials' },
  { symbol: 'DTE', name: 'DTE Inc.', sector: 'Industrials' },
  { symbol: 'DTM', name: 'DTM Inc.', sector: 'Industrials' },
  { symbol: 'DUK', name: 'DUK Inc.', sector: 'Utilities' },
  { symbol: 'DUOL', name: 'DUOL Inc.', sector: 'Industrials' },
  { symbol: 'DVA', name: 'DVA Inc.', sector: 'Industrials' },
  { symbol: 'DVN', name: 'DVN Inc.', sector: 'Energy' },
  { symbol: 'DXCM', name: 'DXCM Inc.', sector: 'Industrials' },
  { symbol: 'DY', name: 'DY Inc.', sector: 'Industrials' },
  { symbol: 'EA', name: 'EA Inc.', sector: 'Communication' },
  { symbol: 'EBAY', name: 'EBAY Inc.', sector: 'Industrials' },
  { symbol: 'ECL', name: 'ECL Inc.', sector: 'Materials' },
  { symbol: 'ED', name: 'ED Inc.', sector: 'Industrials' },
  { symbol: 'EEFT', name: 'EEFT Inc.', sector: 'Industrials' },
  { symbol: 'EFX', name: 'EFX Inc.', sector: 'Industrials' },
  { symbol: 'EG', name: 'EG Inc.', sector: 'Industrials' },
  { symbol: 'EGP', name: 'EGP Inc.', sector: 'Industrials' },
  { symbol: 'EHC', name: 'EHC Inc.', sector: 'Industrials' },
  { symbol: 'EIX', name: 'EIX Inc.', sector: 'Industrials' },
  { symbol: 'EL', name: 'EL Inc.', sector: 'Industrials' },
  { symbol: 'ELAN', name: 'ELAN Inc.', sector: 'Industrials' },
  { symbol: 'ELF', name: 'ELF Inc.', sector: 'Industrials' },
  { symbol: 'ELS', name: 'ELS Inc.', sector: 'Industrials' },
  { symbol: 'ELV', name: 'ELV Inc.', sector: 'Industrials' },
  { symbol: 'EME', name: 'EME Inc.', sector: 'Industrials' },
  { symbol: 'EMR', name: 'EMR Inc.', sector: 'Industrials' },
  { symbol: 'ENS', name: 'ENS Inc.', sector: 'Industrials' },
  { symbol: 'ENSG', name: 'ENSG Inc.', sector: 'Industrials' },
  { symbol: 'ENTG', name: 'ENTG Inc.', sector: 'Industrials' },
  { symbol: 'EOG', name: 'EOG Inc.', sector: 'Energy' },
  { symbol: 'EPAM', name: 'EPAM Inc.', sector: 'Industrials' },
  { symbol: 'EPR', name: 'EPR Inc.', sector: 'Industrials' },
  { symbol: 'EQH', name: 'EQH Inc.', sector: 'Industrials' },
  { symbol: 'EQIX', name: 'EQIX Inc.', sector: 'Real Estate' },
  { symbol: 'EQR', name: 'EQR Inc.', sector: 'Industrials' },
  { symbol: 'EQT', name: 'EQT Inc.', sector: 'Industrials' },
  { symbol: 'ERIE', name: 'ERIE Inc.', sector: 'Industrials' },
  { symbol: 'ES', name: 'ES Inc.', sector: 'Industrials' },
  { symbol: 'ESAB', name: 'ESAB Inc.', sector: 'Industrials' },
  { symbol: 'ESNT', name: 'ESNT Inc.', sector: 'Industrials' },
  { symbol: 'ESS', name: 'ESS Inc.', sector: 'Industrials' },
  { symbol: 'ETN', name: 'ETN Inc.', sector: 'Industrials' },
  { symbol: 'ETR', name: 'ETR Inc.', sector: 'Industrials' },
  { symbol: 'EVR', name: 'EVR Inc.', sector: 'Industrials' },
  { symbol: 'EVRG', name: 'EVRG Inc.', sector: 'Industrials' },
  { symbol: 'EW', name: 'EW Inc.', sector: 'Industrials' },
  { symbol: 'EWBC', name: 'EWBC Inc.', sector: 'Industrials' },
  { symbol: 'EXC', name: 'EXC Inc.', sector: 'Utilities' },
  { symbol: 'EXE', name: 'EXE Inc.', sector: 'Industrials' },
  { symbol: 'EXEL', name: 'EXEL Inc.', sector: 'Industrials' },
  { symbol: 'EXLS', name: 'EXLS Inc.', sector: 'Industrials' },
  { symbol: 'EXP', name: 'EXP Inc.', sector: 'Industrials' },
  { symbol: 'EXPD', name: 'EXPD Inc.', sector: 'Industrials' },
  { symbol: 'EXPE', name: 'EXPE Inc.', sector: 'Industrials' },
  { symbol: 'EXPO', name: 'EXPO Inc.', sector: 'Industrials' },
  { symbol: 'EXR', name: 'EXR Inc.', sector: 'Real Estate' },
  { symbol: 'F', name: 'F Inc.', sector: 'Industrials' },
  { symbol: 'FAF', name: 'FAF Inc.', sector: 'Industrials' },
  { symbol: 'FANG', name: 'FANG Inc.', sector: 'Industrials' },
  { symbol: 'FAST', name: 'FAST Inc.', sector: 'Industrials' },
  { symbol: 'FBIN', name: 'FBIN Inc.', sector: 'Industrials' },
  { symbol: 'FCFS', name: 'FCFS Inc.', sector: 'Industrials' },
  { symbol: 'FCN', name: 'FCN Inc.', sector: 'Industrials' },
  { symbol: 'FCX', name: 'FCX Inc.', sector: 'Materials' },
  { symbol: 'FDS', name: 'FDS Inc.', sector: 'Industrials' },
  { symbol: 'FDX', name: 'FDX Inc.', sector: 'Industrials' },
  { symbol: 'FE', name: 'FE Inc.', sector: 'Industrials' },
  { symbol: 'FFIN', name: 'FFIN Inc.', sector: 'Industrials' },
  { symbol: 'FFIV', name: 'FFIV Inc.', sector: 'Industrials' },
  { symbol: 'FHI', name: 'FHI Inc.', sector: 'Industrials' },
  { symbol: 'FHN', name: 'FHN Inc.', sector: 'Industrials' },
  { symbol: 'FICO', name: 'FICO Inc.', sector: 'Industrials' },
  { symbol: 'FIS', name: 'FIS Inc.', sector: 'Industrials' },
  { symbol: 'FISV', name: 'FISV Inc.', sector: 'Industrials' },
  { symbol: 'FITB', name: 'FITB Inc.', sector: 'Industrials' },
  { symbol: 'FIVE', name: 'FIVE Inc.', sector: 'Industrials' },
  { symbol: 'FIX', name: 'FIX Inc.', sector: 'Industrials' },
  { symbol: 'FLEX', name: 'FLEX Inc.', sector: 'Industrials' },
  { symbol: 'FLG', name: 'FLG Inc.', sector: 'Industrials' },
  { symbol: 'FLO', name: 'FLO Inc.', sector: 'Industrials' },
  { symbol: 'FLR', name: 'FLR Inc.', sector: 'Industrials' },
  { symbol: 'FLS', name: 'FLS Inc.', sector: 'Industrials' },
  { symbol: 'FN', name: 'FN Inc.', sector: 'Industrials' },
  { symbol: 'FNB', name: 'FNB Inc.', sector: 'Industrials' },
  { symbol: 'FND', name: 'FND Inc.', sector: 'Industrials' },
  { symbol: 'FNF', name: 'FNF Inc.', sector: 'Industrials' },
  { symbol: 'FOUR', name: 'FOUR Inc.', sector: 'Industrials' },
  { symbol: 'FOX', name: 'FOX Inc.', sector: 'Industrials' },
  { symbol: 'FOXA', name: 'FOXA Inc.', sector: 'Industrials' },
  { symbol: 'FR', name: 'FR Inc.', sector: 'Industrials' },
  { symbol: 'FRT', name: 'FRT Inc.', sector: 'Industrials' },
  { symbol: 'FSLR', name: 'FSLR Inc.', sector: 'Industrials' },
  { symbol: 'FTI', name: 'FTI Inc.', sector: 'Industrials' },
  { symbol: 'FTNT', name: 'FTNT Inc.', sector: 'Technology' },
  { symbol: 'FTV', name: 'FTV Inc.', sector: 'Industrials' },
  { symbol: 'G', name: 'G Inc.', sector: 'Industrials' },
  { symbol: 'GAP', name: 'GAP Inc.', sector: 'Industrials' },
  { symbol: 'GATX', name: 'GATX Inc.', sector: 'Industrials' },
  { symbol: 'GBCI', name: 'GBCI Inc.', sector: 'Industrials' },
  { symbol: 'GD', name: 'GD Inc.', sector: 'Industrials' },
  { symbol: 'GDDY', name: 'GDDY Inc.', sector: 'Industrials' },
  { symbol: 'GE', name: 'GE Aerospace', sector: 'Industrials' },
  { symbol: 'GEF', name: 'GEF Inc.', sector: 'Industrials' },
  { symbol: 'GEHC', name: 'GEHC Inc.', sector: 'Industrials' },
  { symbol: 'GEN', name: 'GEN Inc.', sector: 'Industrials' },
  { symbol: 'GEV', name: 'GEV Inc.', sector: 'Industrials' },
  { symbol: 'GGG', name: 'GGG Inc.', sector: 'Industrials' },
  { symbol: 'GHC', name: 'GHC Inc.', sector: 'Industrials' },
  { symbol: 'GILD', name: 'GILD Inc.', sector: 'Healthcare' },
  { symbol: 'GIS', name: 'GIS Inc.', sector: 'Staples' },
  { symbol: 'GL', name: 'GL Inc.', sector: 'Industrials' },
  { symbol: 'GLPI', name: 'GLPI Inc.', sector: 'Industrials' },
  { symbol: 'GLW', name: 'GLW Inc.', sector: 'Industrials' },
  { symbol: 'GM', name: 'GM Inc.', sector: 'Industrials' },
  { symbol: 'GME', name: 'GME Inc.', sector: 'Industrials' },
  { symbol: 'GMED', name: 'GMED Inc.', sector: 'Industrials' },
  { symbol: 'GNRC', name: 'GNRC Inc.', sector: 'Industrials' },
  { symbol: 'GNTX', name: 'GNTX Inc.', sector: 'Industrials' },
  { symbol: 'GOOG', name: 'Alphabet C', sector: 'Communication' },
  { symbol: 'GOOGL', name: 'Alphabet A', sector: 'Communication' },
  { symbol: 'GPC', name: 'GPC Inc.', sector: 'Industrials' },
  { symbol: 'GPK', name: 'GPK Inc.', sector: 'Industrials' },
  { symbol: 'GPN', name: 'GPN Inc.', sector: 'Industrials' },
  { symbol: 'GRMN', name: 'GRMN Inc.', sector: 'Industrials' },
  { symbol: 'GS', name: 'Goldman Sachs', sector: 'Financials' },
  { symbol: 'GT', name: 'GT Inc.', sector: 'Industrials' },
  { symbol: 'GTLS', name: 'GTLS Inc.', sector: 'Industrials' },
  { symbol: 'GWRE', name: 'GWRE Inc.', sector: 'Industrials' },
  { symbol: 'GWW', name: 'GWW Inc.', sector: 'Industrials' },
  { symbol: 'GXO', name: 'GXO Inc.', sector: 'Industrials' },
  { symbol: 'H', name: 'H Inc.', sector: 'Industrials' },
  { symbol: 'HAE', name: 'HAE Inc.', sector: 'Industrials' },
  { symbol: 'HAL', name: 'HAL Inc.', sector: 'Energy' },
  { symbol: 'HALO', name: 'HALO Inc.', sector: 'Industrials' },
  { symbol: 'HAS', name: 'HAS Inc.', sector: 'Industrials' },
  { symbol: 'HBAN', name: 'HBAN Inc.', sector: 'Industrials' },
  { symbol: 'HCA', name: 'HCA Inc.', sector: 'Industrials' },
  { symbol: 'HD', name: 'Home Depot', sector: 'Consumer Disc.' },
  { symbol: 'HGV', name: 'HGV Inc.', sector: 'Industrials' },
  { symbol: 'HIG', name: 'HIG Inc.', sector: 'Industrials' },
  { symbol: 'HII', name: 'HII Inc.', sector: 'Industrials' },
  { symbol: 'HIMS', name: 'HIMS Inc.', sector: 'Industrials' },
  { symbol: 'HL', name: 'HL Inc.', sector: 'Industrials' },
  { symbol: 'HLI', name: 'HLI Inc.', sector: 'Industrials' },
  { symbol: 'HLNE', name: 'HLNE Inc.', sector: 'Industrials' },
  { symbol: 'HLT', name: 'HLT Inc.', sector: 'Industrials' },
  { symbol: 'HOG', name: 'HOG Inc.', sector: 'Industrials' },
  { symbol: 'HOLX', name: 'HOLX Inc.', sector: 'Industrials' },
  { symbol: 'HOMB', name: 'HOMB Inc.', sector: 'Industrials' },
  { symbol: 'HON', name: 'Honeywell', sector: 'Industrials' },
  { symbol: 'HOOD', name: 'HOOD Inc.', sector: 'Industrials' },
  { symbol: 'HPE', name: 'HPE Inc.', sector: 'Industrials' },
  { symbol: 'HPQ', name: 'HPQ Inc.', sector: 'Industrials' },
  { symbol: 'HQY', name: 'HQY Inc.', sector: 'Industrials' },
  { symbol: 'HR', name: 'HR Inc.', sector: 'Industrials' },
  { symbol: 'HRB', name: 'HRB Inc.', sector: 'Industrials' },
  { symbol: 'HRL', name: 'HRL Inc.', sector: 'Industrials' },
  { symbol: 'HSIC', name: 'HSIC Inc.', sector: 'Industrials' },
  { symbol: 'HST', name: 'HST Inc.', sector: 'Industrials' },
  { symbol: 'HSY', name: 'HSY Inc.', sector: 'Industrials' },
  { symbol: 'HUBB', name: 'HUBB Inc.', sector: 'Industrials' },
  { symbol: 'HUM', name: 'HUM Inc.', sector: 'Industrials' },
  { symbol: 'HWC', name: 'HWC Inc.', sector: 'Industrials' },
  { symbol: 'HWM', name: 'HWM Inc.', sector: 'Industrials' },
  { symbol: 'HXL', name: 'HXL Inc.', sector: 'Industrials' },
  { symbol: 'IBKR', name: 'IBKR Inc.', sector: 'Industrials' },
  { symbol: 'IBM', name: 'IBM Inc.', sector: 'Technology' },
  { symbol: 'IBOC', name: 'IBOC Inc.', sector: 'Industrials' },
  { symbol: 'ICE', name: 'ICE Inc.', sector: 'Industrials' },
  { symbol: 'IDA', name: 'IDA Inc.', sector: 'Industrials' },
  { symbol: 'IDCC', name: 'IDCC Inc.', sector: 'Industrials' },
  { symbol: 'IDXX', name: 'IDXX Inc.', sector: 'Industrials' },
  { symbol: 'IEX', name: 'IEX Inc.', sector: 'Industrials' },
  { symbol: 'IFF', name: 'IFF Inc.', sector: 'Industrials' },
  { symbol: 'ILMN', name: 'ILMN Inc.', sector: 'Industrials' },
  { symbol: 'INCY', name: 'INCY Inc.', sector: 'Industrials' },
  { symbol: 'INGR', name: 'INGR Inc.', sector: 'Industrials' },
  { symbol: 'INTC', name: 'INTC Inc.', sector: 'Industrials' },
  { symbol: 'INTU', name: 'Intuit', sector: 'Technology' },
  { symbol: 'INVH', name: 'INVH Inc.', sector: 'Industrials' },
  { symbol: 'IP', name: 'IP Inc.', sector: 'Industrials' },
  { symbol: 'IPGP', name: 'IPGP Inc.', sector: 'Industrials' },
  { symbol: 'IQV', name: 'IQV Inc.', sector: 'Industrials' },
  { symbol: 'IR', name: 'IR Inc.', sector: 'Industrials' },
  { symbol: 'IRM', name: 'IRM Inc.', sector: 'Industrials' },
  { symbol: 'IRT', name: 'IRT Inc.', sector: 'Industrials' },
  { symbol: 'ISRG', name: 'ISRG Inc.', sector: 'Healthcare' },
  { symbol: 'IT', name: 'IT Inc.', sector: 'Industrials' },
  { symbol: 'ITT', name: 'ITT Inc.', sector: 'Industrials' },
  { symbol: 'ITW', name: 'ITW Inc.', sector: 'Industrials' },
  { symbol: 'IVZ', name: 'IVZ Inc.', sector: 'Industrials' },
  { symbol: 'J', name: 'J Inc.', sector: 'Industrials' },
  { symbol: 'JAZZ', name: 'JAZZ Inc.', sector: 'Industrials' },
  { symbol: 'JBHT', name: 'JBHT Inc.', sector: 'Industrials' },
  { symbol: 'JBL', name: 'JBL Inc.', sector: 'Industrials' },
  { symbol: 'JCI', name: 'JCI Inc.', sector: 'Industrials' },
  { symbol: 'JEF', name: 'JEF Inc.', sector: 'Industrials' },
  { symbol: 'JHG', name: 'JHG Inc.', sector: 'Industrials' },
  { symbol: 'JKHY', name: 'JKHY Inc.', sector: 'Industrials' },
  { symbol: 'JLL', name: 'JLL Inc.', sector: 'Industrials' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare' },
  { symbol: 'JPM', name: 'JPMorgan Chase', sector: 'Financials' },
  { symbol: 'KBH', name: 'KBH Inc.', sector: 'Industrials' },
  { symbol: 'KBR', name: 'KBR Inc.', sector: 'Industrials' },
  { symbol: 'KD', name: 'KD Inc.', sector: 'Industrials' },
  { symbol: 'KDP', name: 'KDP Inc.', sector: 'Industrials' },
  { symbol: 'KEX', name: 'KEX Inc.', sector: 'Industrials' },
  { symbol: 'KEY', name: 'KEY Inc.', sector: 'Industrials' },
  { symbol: 'KEYS', name: 'KEYS Inc.', sector: 'Industrials' },
  { symbol: 'KHC', name: 'KHC Inc.', sector: 'Industrials' },
  { symbol: 'KIM', name: 'KIM Inc.', sector: 'Industrials' },
  { symbol: 'KKR', name: 'KKR Inc.', sector: 'Industrials' },
  { symbol: 'KLAC', name: 'KLAC Inc.', sector: 'Technology' },
  { symbol: 'KMB', name: 'KMB Inc.', sector: 'Industrials' },
  { symbol: 'KMI', name: 'KMI Inc.', sector: 'Industrials' },
  { symbol: 'KNF', name: 'KNF Inc.', sector: 'Industrials' },
  { symbol: 'KNSL', name: 'KNSL Inc.', sector: 'Industrials' },
  { symbol: 'KNX', name: 'KNX Inc.', sector: 'Industrials' },
  { symbol: 'KO', name: 'Coca-Cola', sector: 'Staples' },
  { symbol: 'KR', name: 'KR Inc.', sector: 'Industrials' },
  { symbol: 'KRC', name: 'KRC Inc.', sector: 'Industrials' },
  { symbol: 'KRG', name: 'KRG Inc.', sector: 'Industrials' },
  { symbol: 'KTOS', name: 'KTOS Inc.', sector: 'Industrials' },
  { symbol: 'KVUE', name: 'KVUE Inc.', sector: 'Industrials' },
  { symbol: 'L', name: 'L Inc.', sector: 'Industrials' },
  { symbol: 'LAD', name: 'LAD Inc.', sector: 'Industrials' },
  { symbol: 'LAMR', name: 'LAMR Inc.', sector: 'Industrials' },
  { symbol: 'LDOS', name: 'LDOS Inc.', sector: 'Industrials' },
  { symbol: 'LEA', name: 'LEA Inc.', sector: 'Industrials' },
  { symbol: 'LECO', name: 'LECO Inc.', sector: 'Industrials' },
  { symbol: 'LEN', name: 'LEN Inc.', sector: 'Industrials' },
  { symbol: 'LFUS', name: 'LFUS Inc.', sector: 'Industrials' },
  { symbol: 'LH', name: 'LH Inc.', sector: 'Industrials' },
  { symbol: 'LHX', name: 'LHX Inc.', sector: 'Industrials' },
  { symbol: 'LII', name: 'LII Inc.', sector: 'Industrials' },
  { symbol: 'LIN', name: 'LIN Inc.', sector: 'Materials' },
  { symbol: 'LITE', name: 'LITE Inc.', sector: 'Industrials' },
  { symbol: 'LIVN', name: 'LIVN Inc.', sector: 'Industrials' },
  { symbol: 'LLY', name: 'Eli Lilly', sector: 'Healthcare' },
  { symbol: 'LMT', name: 'Lockheed Martin', sector: 'Industrials' },
  { symbol: 'LNT', name: 'LNT Inc.', sector: 'Industrials' },
  { symbol: 'LNTH', name: 'LNTH Inc.', sector: 'Industrials' },
  { symbol: 'LOPE', name: 'LOPE Inc.', sector: 'Industrials' },
  { symbol: 'LOW', name: 'Lowe\'s', sector: 'Consumer Disc.' },
  { symbol: 'LPX', name: 'LPX Inc.', sector: 'Industrials' },
  { symbol: 'LRCX', name: 'LRCX Inc.', sector: 'Technology' },
  { symbol: 'LSCC', name: 'LSCC Inc.', sector: 'Industrials' },
  { symbol: 'LSTR', name: 'LSTR Inc.', sector: 'Industrials' },
  { symbol: 'LULU', name: 'LULU Inc.', sector: 'Industrials' },
  { symbol: 'LUV', name: 'LUV Inc.', sector: 'Industrials' },
  { symbol: 'LVS', name: 'LVS Inc.', sector: 'Industrials' },
  { symbol: 'LYB', name: 'LYB Inc.', sector: 'Industrials' },
  { symbol: 'LYV', name: 'LYV Inc.', sector: 'Industrials' },
  { symbol: 'M', name: 'M Inc.', sector: 'Industrials' },
  { symbol: 'MA', name: 'Mastercard', sector: 'Financials' },
  { symbol: 'MAA', name: 'MAA Inc.', sector: 'Industrials' },
  { symbol: 'MANH', name: 'MANH Inc.', sector: 'Industrials' },
  { symbol: 'MAR', name: 'MAR Inc.', sector: 'Industrials' },
  { symbol: 'MAS', name: 'MAS Inc.', sector: 'Industrials' },
  { symbol: 'MASI', name: 'MASI Inc.', sector: 'Industrials' },
  { symbol: 'MAT', name: 'MAT Inc.', sector: 'Industrials' },
  { symbol: 'MCD', name: 'MCD Inc.', sector: 'Consumer Disc.' },
  { symbol: 'MCHP', name: 'MCHP Inc.', sector: 'Technology' },
  { symbol: 'MCK', name: 'MCK Inc.', sector: 'Industrials' },
  { symbol: 'MCO', name: 'MCO Inc.', sector: 'Industrials' },
  { symbol: 'MDLZ', name: 'MDLZ Inc.', sector: 'Staples' },
  { symbol: 'MDT', name: 'Medtronic', sector: 'Healthcare' },
  { symbol: 'MEDP', name: 'MEDP Inc.', sector: 'Industrials' },
  { symbol: 'MET', name: 'MET Inc.', sector: 'Industrials' },
  { symbol: 'META', name: 'Meta', sector: 'Communication' },
  { symbol: 'MGM', name: 'MGM Inc.', sector: 'Industrials' },
  { symbol: 'MIDD', name: 'MIDD Inc.', sector: 'Industrials' },
  { symbol: 'MKC', name: 'MKC Inc.', sector: 'Industrials' },
  { symbol: 'MKSI', name: 'MKSI Inc.', sector: 'Industrials' },
  { symbol: 'MLI', name: 'MLI Inc.', sector: 'Industrials' },
  { symbol: 'MLM', name: 'MLM Inc.', sector: 'Industrials' },
  { symbol: 'MMM', name: 'MMM Inc.', sector: 'Industrials' },
  { symbol: 'MMS', name: 'MMS Inc.', sector: 'Industrials' },
  { symbol: 'MNST', name: 'MNST Inc.', sector: 'Industrials' },
  { symbol: 'MO', name: 'MO Inc.', sector: 'Staples' },
  { symbol: 'MOG.A', name: 'MOG.A Inc.', sector: 'Industrials' },
  { symbol: 'MORN', name: 'MORN Inc.', sector: 'Industrials' },
  { symbol: 'MOS', name: 'MOS Inc.', sector: 'Industrials' },
  { symbol: 'MP', name: 'MP Inc.', sector: 'Industrials' },
  { symbol: 'MPC', name: 'MPC Inc.', sector: 'Energy' },
  { symbol: 'MPWR', name: 'MPWR Inc.', sector: 'Industrials' },
  { symbol: 'MRK', name: 'Merck', sector: 'Healthcare' },
  { symbol: 'MRNA', name: 'MRNA Inc.', sector: 'Industrials' },
  { symbol: 'MRSH', name: 'MRSH Inc.', sector: 'Industrials' },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'Financials' },
  { symbol: 'MSA', name: 'MSA Inc.', sector: 'Industrials' },
  { symbol: 'MSCI', name: 'MSCI Inc.', sector: 'Industrials' },
  { symbol: 'MSFT', name: 'Microsoft', sector: 'Technology' },
  { symbol: 'MSI', name: 'MSI Inc.', sector: 'Industrials' },
  { symbol: 'MSM', name: 'MSM Inc.', sector: 'Industrials' },
  { symbol: 'MTB', name: 'MTB Inc.', sector: 'Industrials' },
  { symbol: 'MTD', name: 'MTD Inc.', sector: 'Industrials' },
  { symbol: 'MTDR', name: 'MTDR Inc.', sector: 'Industrials' },
  { symbol: 'MTG', name: 'MTG Inc.', sector: 'Industrials' },
  { symbol: 'MTN', name: 'MTN Inc.', sector: 'Industrials' },
  { symbol: 'MTSI', name: 'MTSI Inc.', sector: 'Industrials' },
  { symbol: 'MTZ', name: 'MTZ Inc.', sector: 'Industrials' },
  { symbol: 'MU', name: 'MU Inc.', sector: 'Technology' },
  { symbol: 'MUR', name: 'MUR Inc.', sector: 'Industrials' },
  { symbol: 'MUSA', name: 'MUSA Inc.', sector: 'Industrials' },
  { symbol: 'MZTI', name: 'MZTI Inc.', sector: 'Industrials' },
  { symbol: 'NBIX', name: 'NBIX Inc.', sector: 'Industrials' },
  { symbol: 'NCLH', name: 'NCLH Inc.', sector: 'Industrials' },
  { symbol: 'NDAQ', name: 'NDAQ Inc.', sector: 'Industrials' },
  { symbol: 'NDSN', name: 'NDSN Inc.', sector: 'Industrials' },
  { symbol: 'NEE', name: 'NextEra Energy', sector: 'Utilities' },
  { symbol: 'NEM', name: 'NEM Inc.', sector: 'Materials' },
  { symbol: 'NEU', name: 'NEU Inc.', sector: 'Industrials' },
  { symbol: 'NFG', name: 'NFG Inc.', sector: 'Industrials' },
  { symbol: 'NFLX', name: 'Netflix', sector: 'Communication' },
  { symbol: 'NI', name: 'NI Inc.', sector: 'Industrials' },
  { symbol: 'NJR', name: 'NJR Inc.', sector: 'Industrials' },
  { symbol: 'NKE', name: 'Nike', sector: 'Consumer Disc.' },
  { symbol: 'NLY', name: 'NLY Inc.', sector: 'Industrials' },
  { symbol: 'NNN', name: 'NNN Inc.', sector: 'Industrials' },
  { symbol: 'NOC', name: 'NOC Inc.', sector: 'Industrials' },
  { symbol: 'NOV', name: 'NOV Inc.', sector: 'Industrials' },
  { symbol: 'NOVT', name: 'NOVT Inc.', sector: 'Industrials' },
  { symbol: 'NOW', name: 'ServiceNow', sector: 'Technology' },
  { symbol: 'NRG', name: 'NRG Inc.', sector: 'Industrials' },
  { symbol: 'NSA', name: 'NSA Inc.', sector: 'Industrials' },
  { symbol: 'NSC', name: 'NSC Inc.', sector: 'Industrials' },
  { symbol: 'NTAP', name: 'NTAP Inc.', sector: 'Industrials' },
  { symbol: 'NTNX', name: 'NTNX Inc.', sector: 'Industrials' },
  { symbol: 'NTRS', name: 'NTRS Inc.', sector: 'Industrials' },
  { symbol: 'NUE', name: 'NUE Inc.', sector: 'Materials' },
  { symbol: 'NVDA', name: 'NVIDIA', sector: 'Technology' },
  { symbol: 'NVR', name: 'NVR Inc.', sector: 'Industrials' },
  { symbol: 'NVST', name: 'NVST Inc.', sector: 'Industrials' },
  { symbol: 'NVT', name: 'NVT Inc.', sector: 'Industrials' },
  { symbol: 'NWE', name: 'NWE Inc.', sector: 'Industrials' },
  { symbol: 'NWS', name: 'NWS Inc.', sector: 'Industrials' },
  { symbol: 'NWSA', name: 'NWSA Inc.', sector: 'Industrials' },
  { symbol: 'NXPI', name: 'NXPI Inc.', sector: 'Industrials' },
  { symbol: 'NXST', name: 'NXST Inc.', sector: 'Industrials' },
  { symbol: 'NXT', name: 'NXT Inc.', sector: 'Industrials' },
  { symbol: 'NYT', name: 'NYT Inc.', sector: 'Industrials' },
  { symbol: 'O', name: 'O Inc.', sector: 'Real Estate' },
  { symbol: 'OC', name: 'OC Inc.', sector: 'Industrials' },
  { symbol: 'ODFL', name: 'ODFL Inc.', sector: 'Industrials' },
  { symbol: 'OGE', name: 'OGE Inc.', sector: 'Industrials' },
  { symbol: 'OGS', name: 'OGS Inc.', sector: 'Industrials' },
  { symbol: 'OHI', name: 'OHI Inc.', sector: 'Industrials' },
  { symbol: 'OKE', name: 'OKE Inc.', sector: 'Industrials' },
  { symbol: 'OKTA', name: 'OKTA Inc.', sector: 'Technology' },
  { symbol: 'OLED', name: 'OLED Inc.', sector: 'Industrials' },
  { symbol: 'OLLI', name: 'OLLI Inc.', sector: 'Industrials' },
  { symbol: 'OLN', name: 'OLN Inc.', sector: 'Industrials' },
  { symbol: 'OMC', name: 'OMC Inc.', sector: 'Industrials' },
  { symbol: 'ON', name: 'ON Inc.', sector: 'Industrials' },
  { symbol: 'ONB', name: 'ONB Inc.', sector: 'Industrials' },
  { symbol: 'ONTO', name: 'ONTO Inc.', sector: 'Industrials' },
  { symbol: 'OPCH', name: 'OPCH Inc.', sector: 'Industrials' },
  { symbol: 'ORA', name: 'ORA Inc.', sector: 'Industrials' },
  { symbol: 'ORCL', name: 'Oracle', sector: 'Technology' },
  { symbol: 'ORI', name: 'ORI Inc.', sector: 'Industrials' },
  { symbol: 'ORLY', name: 'ORLY Inc.', sector: 'Industrials' },
  { symbol: 'OSK', name: 'OSK Inc.', sector: 'Industrials' },
  { symbol: 'OTIS', name: 'OTIS Inc.', sector: 'Industrials' },
  { symbol: 'OVV', name: 'OVV Inc.', sector: 'Industrials' },
  { symbol: 'OXY', name: 'OXY Inc.', sector: 'Energy' },
  { symbol: 'OZK', name: 'OZK Inc.', sector: 'Industrials' },
  { symbol: 'PAG', name: 'PAG Inc.', sector: 'Industrials' },
  { symbol: 'PANW', name: 'Palo Alto', sector: 'Technology' },
  { symbol: 'PATH', name: 'PATH Inc.', sector: 'Industrials' },
  { symbol: 'PAYX', name: 'PAYX Inc.', sector: 'Industrials' },
  { symbol: 'PB', name: 'PB Inc.', sector: 'Industrials' },
  { symbol: 'PBF', name: 'PBF Inc.', sector: 'Industrials' },
  { symbol: 'PCAR', name: 'PCAR Inc.', sector: 'Industrials' },
  { symbol: 'PCG', name: 'PCG Inc.', sector: 'Industrials' },
  { symbol: 'PCTY', name: 'PCTY Inc.', sector: 'Industrials' },
  { symbol: 'PEG', name: 'PEG Inc.', sector: 'Industrials' },
  { symbol: 'PEGA', name: 'PEGA Inc.', sector: 'Industrials' },
  { symbol: 'PEN', name: 'PEN Inc.', sector: 'Industrials' },
  { symbol: 'PEP', name: 'PepsiCo', sector: 'Staples' },
  { symbol: 'PFE', name: 'Pfizer', sector: 'Healthcare' },
  { symbol: 'PFG', name: 'PFG Inc.', sector: 'Industrials' },
  { symbol: 'PFGC', name: 'PFGC Inc.', sector: 'Industrials' },
  { symbol: 'PG', name: 'Procter & Gamble', sector: 'Staples' },
  { symbol: 'PGR', name: 'PGR Inc.', sector: 'Industrials' },
  { symbol: 'PH', name: 'PH Inc.', sector: 'Industrials' },
  { symbol: 'PHM', name: 'PHM Inc.', sector: 'Industrials' },
  { symbol: 'PII', name: 'PII Inc.', sector: 'Industrials' },
  { symbol: 'PINS', name: 'PINS Inc.', sector: 'Industrials' },
  { symbol: 'PK', name: 'PK Inc.', sector: 'Industrials' },
  { symbol: 'PKG', name: 'PKG Inc.', sector: 'Industrials' },
  { symbol: 'PLD', name: 'PLD Inc.', sector: 'Real Estate' },
  { symbol: 'PLNT', name: 'PLNT Inc.', sector: 'Industrials' },
  { symbol: 'PLTR', name: 'PLTR Inc.', sector: 'Technology' },
  { symbol: 'PM', name: 'Philip Morris', sector: 'Staples' },
  { symbol: 'PNC', name: 'PNC Inc.', sector: 'Financials' },
  { symbol: 'PNFP', name: 'PNFP Inc.', sector: 'Industrials' },
  { symbol: 'PNR', name: 'PNR Inc.', sector: 'Industrials' },
  { symbol: 'PNW', name: 'PNW Inc.', sector: 'Industrials' },
  { symbol: 'PODD', name: 'PODD Inc.', sector: 'Industrials' },
  { symbol: 'POOL', name: 'POOL Inc.', sector: 'Industrials' },
  { symbol: 'POR', name: 'POR Inc.', sector: 'Industrials' },
  { symbol: 'POST', name: 'POST Inc.', sector: 'Industrials' },
  { symbol: 'PPC', name: 'PPC Inc.', sector: 'Industrials' },
  { symbol: 'PPG', name: 'PPG Inc.', sector: 'Industrials' },
  { symbol: 'PPL', name: 'PPL Inc.', sector: 'Industrials' },
  { symbol: 'PR', name: 'PR Inc.', sector: 'Industrials' },
  { symbol: 'PRI', name: 'PRI Inc.', sector: 'Industrials' },
  { symbol: 'PRU', name: 'PRU Inc.', sector: 'Industrials' },
  { symbol: 'PSA', name: 'PSA Inc.', sector: 'Real Estate' },
  { symbol: 'PSKY', name: 'PSKY Inc.', sector: 'Industrials' },
  { symbol: 'PSN', name: 'PSN Inc.', sector: 'Industrials' },
  { symbol: 'PSTG', name: 'PSTG Inc.', sector: 'Industrials' },
  { symbol: 'PSX', name: 'PSX Inc.', sector: 'Energy' },
  { symbol: 'PTC', name: 'PTC Inc.', sector: 'Industrials' },
  { symbol: 'PVH', name: 'PVH Inc.', sector: 'Industrials' },
  { symbol: 'PWR', name: 'PWR Inc.', sector: 'Industrials' },
  { symbol: 'PYPL', name: 'PYPL Inc.', sector: 'Financials' },
  { symbol: 'Q', name: 'Q Inc.', sector: 'Industrials' },
  { symbol: 'QCOM', name: 'Qualcomm', sector: 'Technology' },
  { symbol: 'QLYS', name: 'QLYS Inc.', sector: 'Industrials' },
  { symbol: 'R', name: 'R Inc.', sector: 'Industrials' },
  { symbol: 'RBA', name: 'RBA Inc.', sector: 'Industrials' },
  { symbol: 'RBC', name: 'RBC Inc.', sector: 'Industrials' },
  { symbol: 'RCL', name: 'RCL Inc.', sector: 'Industrials' },
  { symbol: 'REG', name: 'REG Inc.', sector: 'Industrials' },
  { symbol: 'REGN', name: 'REGN Inc.', sector: 'Healthcare' },
  { symbol: 'REXR', name: 'REXR Inc.', sector: 'Industrials' },
  { symbol: 'RF', name: 'RF Inc.', sector: 'Industrials' },
  { symbol: 'RGA', name: 'RGA Inc.', sector: 'Industrials' },
  { symbol: 'RGEN', name: 'RGEN Inc.', sector: 'Industrials' },
  { symbol: 'RGLD', name: 'RGLD Inc.', sector: 'Industrials' },
  { symbol: 'RH', name: 'RH Inc.', sector: 'Industrials' },
  { symbol: 'RJF', name: 'RJF Inc.', sector: 'Industrials' },
  { symbol: 'RL', name: 'RL Inc.', sector: 'Industrials' },
  { symbol: 'RLI', name: 'RLI Inc.', sector: 'Industrials' },
  { symbol: 'RMBS', name: 'RMBS Inc.', sector: 'Industrials' },
  { symbol: 'RMD', name: 'RMD Inc.', sector: 'Industrials' },
  { symbol: 'RNR', name: 'RNR Inc.', sector: 'Industrials' },
  { symbol: 'ROIV', name: 'ROIV Inc.', sector: 'Industrials' },
  { symbol: 'ROK', name: 'ROK Inc.', sector: 'Industrials' },
  { symbol: 'ROL', name: 'ROL Inc.', sector: 'Industrials' },
  { symbol: 'ROP', name: 'ROP Inc.', sector: 'Industrials' },
  { symbol: 'ROST', name: 'ROST Inc.', sector: 'Industrials' },
  { symbol: 'RPM', name: 'RPM Inc.', sector: 'Industrials' },
  { symbol: 'RRC', name: 'RRC Inc.', sector: 'Industrials' },
  { symbol: 'RRX', name: 'RRX Inc.', sector: 'Industrials' },
  { symbol: 'RS', name: 'RS Inc.', sector: 'Industrials' },
  { symbol: 'RSG', name: 'RSG Inc.', sector: 'Industrials' },
  { symbol: 'RTX', name: 'Raytheon', sector: 'Industrials' },
  { symbol: 'RVTY', name: 'RVTY Inc.', sector: 'Industrials' },
  { symbol: 'RYAN', name: 'RYAN Inc.', sector: 'Industrials' },
  { symbol: 'RYN', name: 'RYN Inc.', sector: 'Industrials' },
  { symbol: 'SAIA', name: 'SAIA Inc.', sector: 'Industrials' },
  { symbol: 'SAIC', name: 'SAIC Inc.', sector: 'Industrials' },
  { symbol: 'SAM', name: 'SAM Inc.', sector: 'Industrials' },
  { symbol: 'SARO', name: 'SARO Inc.', sector: 'Industrials' },
  { symbol: 'SATS', name: 'SATS Inc.', sector: 'Industrials' },
  { symbol: 'SBAC', name: 'SBAC Inc.', sector: 'Industrials' },
  { symbol: 'SBRA', name: 'SBRA Inc.', sector: 'Industrials' },
  { symbol: 'SBUX', name: 'Starbucks', sector: 'Consumer Disc.' },
  { symbol: 'SCHW', name: 'SCHW Inc.', sector: 'Financials' },
  { symbol: 'SCI', name: 'SCI Inc.', sector: 'Industrials' },
  { symbol: 'SEIC', name: 'SEIC Inc.', sector: 'Industrials' },
  { symbol: 'SF', name: 'SF Inc.', sector: 'Industrials' },
  { symbol: 'SFM', name: 'SFM Inc.', sector: 'Industrials' },
  { symbol: 'SGI', name: 'SGI Inc.', sector: 'Industrials' },
  { symbol: 'SHC', name: 'SHC Inc.', sector: 'Industrials' },
  { symbol: 'SHW', name: 'SHW Inc.', sector: 'Materials' },
  { symbol: 'SIGI', name: 'SIGI Inc.', sector: 'Industrials' },
  { symbol: 'SITM', name: 'SITM Inc.', sector: 'Industrials' },
  { symbol: 'SJM', name: 'SJM Inc.', sector: 'Industrials' },
  { symbol: 'SLAB', name: 'SLAB Inc.', sector: 'Industrials' },
  { symbol: 'SLB', name: 'SLB Inc.', sector: 'Energy' },
  { symbol: 'SLGN', name: 'SLGN Inc.', sector: 'Industrials' },
  { symbol: 'SLM', name: 'SLM Inc.', sector: 'Industrials' },
  { symbol: 'SMCI', name: 'SMCI Inc.', sector: 'Industrials' },
  { symbol: 'SMG', name: 'SMG Inc.', sector: 'Industrials' },
  { symbol: 'SNA', name: 'SNA Inc.', sector: 'Industrials' },
  { symbol: 'SNDK', name: 'SNDK Inc.', sector: 'Industrials' },
  { symbol: 'SNPS', name: 'SNPS Inc.', sector: 'Technology' },
  { symbol: 'SNX', name: 'SNX Inc.', sector: 'Industrials' },
  { symbol: 'SO', name: 'SO Inc.', sector: 'Utilities' },
  { symbol: 'SOLS', name: 'SOLS Inc.', sector: 'Industrials' },
  { symbol: 'SOLV', name: 'SOLV Inc.', sector: 'Industrials' },
  { symbol: 'SON', name: 'SON Inc.', sector: 'Industrials' },
  { symbol: 'SPG', name: 'SPG Inc.', sector: 'Real Estate' },
  { symbol: 'SPGI', name: 'SPGI Inc.', sector: 'Industrials' },
  { symbol: 'SPXC', name: 'SPXC Inc.', sector: 'Industrials' },
  { symbol: 'SR', name: 'SR Inc.', sector: 'Industrials' },
  { symbol: 'SRE', name: 'SRE Inc.', sector: 'Utilities' },
  { symbol: 'SSB', name: 'SSB Inc.', sector: 'Industrials' },
  { symbol: 'SSD', name: 'SSD Inc.', sector: 'Industrials' },
  { symbol: 'ST', name: 'ST Inc.', sector: 'Industrials' },
  { symbol: 'STAG', name: 'STAG Inc.', sector: 'Industrials' },
  { symbol: 'STE', name: 'STE Inc.', sector: 'Industrials' },
  { symbol: 'STLD', name: 'STLD Inc.', sector: 'Industrials' },
  { symbol: 'STRL', name: 'STRL Inc.', sector: 'Industrials' },
  { symbol: 'STT', name: 'STT Inc.', sector: 'Industrials' },
  { symbol: 'STWD', name: 'STWD Inc.', sector: 'Industrials' },
  { symbol: 'STX', name: 'STX Inc.', sector: 'Industrials' },
  { symbol: 'STZ', name: 'STZ Inc.', sector: 'Industrials' },
  { symbol: 'SW', name: 'SW Inc.', sector: 'Industrials' },
  { symbol: 'SWK', name: 'SWK Inc.', sector: 'Industrials' },
  { symbol: 'SWKS', name: 'SWKS Inc.', sector: 'Industrials' },
  { symbol: 'SWX', name: 'SWX Inc.', sector: 'Industrials' },
  { symbol: 'SYF', name: 'SYF Inc.', sector: 'Industrials' },
  { symbol: 'SYK', name: 'SYK Inc.', sector: 'Industrials' },
  { symbol: 'SYNA', name: 'SYNA Inc.', sector: 'Industrials' },
  { symbol: 'SYY', name: 'SYY Inc.', sector: 'Industrials' },
  { symbol: 'T', name: 'AT&T', sector: 'Communication' },
  { symbol: 'TAP', name: 'TAP Inc.', sector: 'Industrials' },
  { symbol: 'TCBI', name: 'TCBI Inc.', sector: 'Industrials' },
  { symbol: 'TDG', name: 'TDG Inc.', sector: 'Industrials' },
  { symbol: 'TDY', name: 'TDY Inc.', sector: 'Industrials' },
  { symbol: 'TECH', name: 'TECH Inc.', sector: 'Industrials' },
  { symbol: 'TEL', name: 'TEL Inc.', sector: 'Industrials' },
  { symbol: 'TER', name: 'TER Inc.', sector: 'Industrials' },
  { symbol: 'TEX', name: 'TEX Inc.', sector: 'Industrials' },
  { symbol: 'TFC', name: 'TFC Inc.', sector: 'Industrials' },
  { symbol: 'TGT', name: 'TGT Inc.', sector: 'Consumer Disc.' },
  { symbol: 'THC', name: 'THC Inc.', sector: 'Industrials' },
  { symbol: 'THG', name: 'THG Inc.', sector: 'Industrials' },
  { symbol: 'THO', name: 'THO Inc.', sector: 'Industrials' },
  { symbol: 'TJX', name: 'TJX Inc.', sector: 'Industrials' },
  { symbol: 'TKO', name: 'TKO Inc.', sector: 'Industrials' },
  { symbol: 'TKR', name: 'TKR Inc.', sector: 'Industrials' },
  { symbol: 'TLN', name: 'TLN Inc.', sector: 'Industrials' },
  { symbol: 'TMHC', name: 'TMHC Inc.', sector: 'Industrials' },
  { symbol: 'TMO', name: 'Thermo Fisher', sector: 'Healthcare' },
  { symbol: 'TMUS', name: 'TMUS Inc.', sector: 'Industrials' },
  { symbol: 'TNL', name: 'TNL Inc.', sector: 'Industrials' },
  { symbol: 'TOL', name: 'TOL Inc.', sector: 'Industrials' },
  { symbol: 'TPL', name: 'TPL Inc.', sector: 'Industrials' },
  { symbol: 'TPR', name: 'TPR Inc.', sector: 'Industrials' },
  { symbol: 'TREX', name: 'TREX Inc.', sector: 'Industrials' },
  { symbol: 'TRGP', name: 'TRGP Inc.', sector: 'Industrials' },
  { symbol: 'TRMB', name: 'TRMB Inc.', sector: 'Industrials' },
  { symbol: 'TROW', name: 'TROW Inc.', sector: 'Industrials' },
  { symbol: 'TRU', name: 'TRU Inc.', sector: 'Industrials' },
  { symbol: 'TRV', name: 'TRV Inc.', sector: 'Industrials' },
  { symbol: 'TSCO', name: 'Tractor Supply', sector: 'Industrials' },
  { symbol: 'TSLA', name: 'Tesla', sector: 'Consumer Disc.' },
  { symbol: 'TSN', name: 'TSN Inc.', sector: 'Industrials' },
  { symbol: 'TT', name: 'TT Inc.', sector: 'Industrials' },
  { symbol: 'TTC', name: 'TTC Inc.', sector: 'Industrials' },
  { symbol: 'TTD', name: 'TTD Inc.', sector: 'Industrials' },
  { symbol: 'TTEK', name: 'TTEK Inc.', sector: 'Industrials' },
  { symbol: 'TTMI', name: 'TTMI Inc.', sector: 'Industrials' },
  { symbol: 'TTWO', name: 'TTWO Inc.', sector: 'Communication' },
  { symbol: 'TWLO', name: 'TWLO Inc.', sector: 'Industrials' },
  { symbol: 'TXN', name: 'Texas Instruments', sector: 'Technology' },
  { symbol: 'TXNM', name: 'TXNM Inc.', sector: 'Industrials' },
  { symbol: 'TXRH', name: 'TXRH Inc.', sector: 'Industrials' },
  { symbol: 'TXT', name: 'TXT Inc.', sector: 'Industrials' },
  { symbol: 'TYL', name: 'TYL Inc.', sector: 'Industrials' },
  { symbol: 'UAL', name: 'UAL Inc.', sector: 'Industrials' },
  { symbol: 'UBER', name: 'Uber', sector: 'Consumer Disc.' },
  { symbol: 'UBSI', name: 'UBSI Inc.', sector: 'Industrials' },
  { symbol: 'UDR', name: 'UDR Inc.', sector: 'Industrials' },
  { symbol: 'UFPI', name: 'UFPI Inc.', sector: 'Industrials' },
  { symbol: 'UGI', name: 'UGI Inc.', sector: 'Industrials' },
  { symbol: 'UHS', name: 'UHS Inc.', sector: 'Industrials' },
  { symbol: 'ULS', name: 'ULS Inc.', sector: 'Industrials' },
  { symbol: 'ULTA', name: 'ULTA Inc.', sector: 'Industrials' },
  { symbol: 'UMBF', name: 'UMBF Inc.', sector: 'Industrials' },
  { symbol: 'UNH', name: 'UnitedHealth', sector: 'Healthcare' },
  { symbol: 'UNM', name: 'UNM Inc.', sector: 'Industrials' },
  { symbol: 'UNP', name: 'UNP Inc.', sector: 'Industrials' },
  { symbol: 'UPS', name: 'UPS', sector: 'Industrials' },
  { symbol: 'URI', name: 'URI Inc.', sector: 'Industrials' },
  { symbol: 'USB', name: 'USB Inc.', sector: 'Financials' },
  { symbol: 'USFD', name: 'USFD Inc.', sector: 'Industrials' },
  { symbol: 'UTHR', name: 'UTHR Inc.', sector: 'Industrials' },
  { symbol: 'V', name: 'Visa', sector: 'Financials' },
  { symbol: 'VAL', name: 'VAL Inc.', sector: 'Industrials' },
  { symbol: 'VC', name: 'VC Inc.', sector: 'Industrials' },
  { symbol: 'VFC', name: 'VFC Inc.', sector: 'Industrials' },
  { symbol: 'VICI', name: 'VICI Inc.', sector: 'Real Estate' },
  { symbol: 'VICR', name: 'VICR Inc.', sector: 'Industrials' },
  { symbol: 'VLO', name: 'VLO Inc.', sector: 'Energy' },
  { symbol: 'VLTO', name: 'VLTO Inc.', sector: 'Industrials' },
  { symbol: 'VLY', name: 'VLY Inc.', sector: 'Industrials' },
  { symbol: 'VMC', name: 'VMC Inc.', sector: 'Industrials' },
  { symbol: 'VMI', name: 'VMI Inc.', sector: 'Industrials' },
  { symbol: 'VNO', name: 'VNO Inc.', sector: 'Industrials' },
  { symbol: 'VNOM', name: 'VNOM Inc.', sector: 'Industrials' },
  { symbol: 'VNT', name: 'VNT Inc.', sector: 'Industrials' },
  { symbol: 'VOYA', name: 'VOYA Inc.', sector: 'Industrials' },
  { symbol: 'VRSK', name: 'VRSK Inc.', sector: 'Industrials' },
  { symbol: 'VRSN', name: 'VRSN Inc.', sector: 'Industrials' },
  { symbol: 'VRT', name: 'VRT Inc.', sector: 'Industrials' },
  { symbol: 'VRTX', name: 'VRTX Inc.', sector: 'Healthcare' },
  { symbol: 'VST', name: 'VST Inc.', sector: 'Industrials' },
  { symbol: 'VTR', name: 'VTR Inc.', sector: 'Industrials' },
  { symbol: 'VTRS', name: 'VTRS Inc.', sector: 'Industrials' },
  { symbol: 'VVV', name: 'VVV Inc.', sector: 'Industrials' },
  { symbol: 'VZ', name: 'Verizon', sector: 'Communication' },
  { symbol: 'WAB', name: 'WAB Inc.', sector: 'Industrials' },
  { symbol: 'WAL', name: 'WAL Inc.', sector: 'Industrials' },
  { symbol: 'WAT', name: 'WAT Inc.', sector: 'Industrials' },
  { symbol: 'WBD', name: 'WBD Inc.', sector: 'Industrials' },
  { symbol: 'WBS', name: 'WBS Inc.', sector: 'Industrials' },
  { symbol: 'WCC', name: 'WCC Inc.', sector: 'Industrials' },
  { symbol: 'WDAY', name: 'WDAY Inc.', sector: 'Industrials' },
  { symbol: 'WDC', name: 'WDC Inc.', sector: 'Industrials' },
  { symbol: 'WEC', name: 'WEC Inc.', sector: 'Industrials' },
  { symbol: 'WELL', name: 'WELL Inc.', sector: 'Real Estate' },
  { symbol: 'WEX', name: 'WEX Inc.', sector: 'Industrials' },
  { symbol: 'WFC', name: 'WFC Inc.', sector: 'Financials' },
  { symbol: 'WFRD', name: 'WFRD Inc.', sector: 'Industrials' },
  { symbol: 'WH', name: 'WH Inc.', sector: 'Industrials' },
  { symbol: 'WHR', name: 'WHR Inc.', sector: 'Industrials' },
  { symbol: 'WING', name: 'WING Inc.', sector: 'Industrials' },
  { symbol: 'WLK', name: 'WLK Inc.', sector: 'Industrials' },
  { symbol: 'WM', name: 'WM Inc.', sector: 'Industrials' },
  { symbol: 'WMB', name: 'WMB Inc.', sector: 'Industrials' },
  { symbol: 'WMG', name: 'WMG Inc.', sector: 'Industrials' },
  { symbol: 'WMS', name: 'WMS Inc.', sector: 'Industrials' },
  { symbol: 'WMT', name: 'Walmart', sector: 'Staples' },
  { symbol: 'WPC', name: 'WPC Inc.', sector: 'Industrials' },
  { symbol: 'WRB', name: 'WRB Inc.', sector: 'Industrials' },
  { symbol: 'WSM', name: 'WSM Inc.', sector: 'Industrials' },
  { symbol: 'WSO', name: 'WSO Inc.', sector: 'Industrials' },
  { symbol: 'WST', name: 'WST Inc.', sector: 'Industrials' },
  { symbol: 'WTFC', name: 'WTFC Inc.', sector: 'Industrials' },
  { symbol: 'WTRG', name: 'WTRG Inc.', sector: 'Industrials' },
  { symbol: 'WTS', name: 'WTS Inc.', sector: 'Industrials' },
  { symbol: 'WTW', name: 'WTW Inc.', sector: 'Industrials' },
  { symbol: 'WWD', name: 'WWD Inc.', sector: 'Industrials' },
  { symbol: 'WY', name: 'WY Inc.', sector: 'Industrials' },
  { symbol: 'WYNN', name: 'WYNN Inc.', sector: 'Industrials' },
  { symbol: 'XEL', name: 'XEL Inc.', sector: 'Utilities' },
  { symbol: 'XOM', name: 'ExxonMobil', sector: 'Energy' },
  { symbol: 'XPO', name: 'XPO Inc.', sector: 'Industrials' },
  { symbol: 'XRAY', name: 'XRAY Inc.', sector: 'Industrials' },
  { symbol: 'XYL', name: 'XYL Inc.', sector: 'Industrials' },
  { symbol: 'XYZ', name: 'XYZ Inc.', sector: 'Industrials' },
  { symbol: 'YETI', name: 'YETI Inc.', sector: 'Industrials' },
  { symbol: 'YUM', name: 'YUM Inc.', sector: 'Industrials' },
  { symbol: 'ZBH', name: 'ZBH Inc.', sector: 'Industrials' },
  { symbol: 'ZBRA', name: 'ZBRA Inc.', sector: 'Industrials' },
  { symbol: 'ZION', name: 'ZION Inc.', sector: 'Industrials' },
  { symbol: 'ZTS', name: 'ZTS Inc.', sector: 'Industrials' },
];

// ── Symbol-only arrays for backward compatibility ───────────────────────────
export const BIST100_SYMBOLS:    string[] = BIST100_LIST.map(s => s.symbol);
export const BIST100DISI_SYMBOLS:string[] = BIST100DISI_LIST.map(s => s.symbol);
export const BISTTUM_SYMBOLS:    string[] = BISTTUM_LIST.map(s => s.symbol);
export const US_MARKET_SYMBOLS:  string[] = US_MARKET_LIST.map(s => s.symbol);

export type UniverseType = 'BISTTUM' | 'BIST100' | 'BIST100DISI' | 'US';

export function getUniverse(type: UniverseType): UniverseStock[] {
  switch (type) {
    case 'BIST100':     return BIST100_LIST;
    case 'BIST100DISI': return BIST100DISI_LIST;
    case 'BISTTUM':     return BISTTUM_LIST;
    case 'US':          return US_MARKET_LIST;
  }
}

export function getUniverseSymbols(type: UniverseType): string[] {
  return getUniverse(type).map(s => s.symbol);
}
